apiVersion: v1
kind: Pod
metadata:
  name: my_nginx_pod
spec:
  containers:
    - name: my_nginx
      image: nginx:latest
      resources:
        limits:
          cpu: "0.5"
          memory: "64Mi"
      securityContext:
        pidsLimit: 10
      restartPolicy: "unless-stopped"
      ports:
        - containerPort: 80
          hostPort: 8080
