Container Manager: utils/inc/aes_gcm_decrypt.hpp File Reference
aes_gcm_decrypt.hpp File Reference
#include <vector>
#include <string>
Functions
bool aes_gcm_decrypt (const std::vector< unsigned char > &ciphertext, const unsigned char *key, const unsigned char *iv, const unsigned char *tag, std::vector< unsigned char > &plaintext)
Decrypts AES-256-GCM encrypted ciphertext.
bool decrypt_ota_payload (const std::string &input, std::string &plaintext)
Decrypts an OTA (over-the-air) payload formatted as [IV|TAG|CIPHERTEXT]. Loads the AES key from file at runtime.
Function Documentation
aes_gcm_decrypt()
bool aes_gcm_decrypt (const std::vector< unsigned char > & ciphertext, const unsigned char * key, const unsigned char * iv, const unsigned char * tag, std::vector< unsigned char > & plaintext)
Decrypts AES-256-GCM encrypted ciphertext.
Decrypts AES-256-GCM encrypted ciphertext.
Parameters
ciphertext The encrypted data (excluding IV and tag).
key The 32-byte AES key.
iv The 12-byte initialization vector (IV).
tag The 16-byte authentication tag.
plaintext Output vector for the decrypted data.
Returns
true on successful decryption and authentication, false otherwise.
Parameters
ciphertext The encrypted data (excluding IV and tag).
key The 32-byte AES key.
iv The 12-byte initialization vector (IV).
tag The 16-byte authentication tag.
plaintext Output vector for the decrypted data.
Returns
true on successful decryption and authentication, false otherwise.
Definition at line 41 of file aes_gcm_decrypt.cpp.
   {
     // Create and initialize the decryption context
     EVP_CIPHER_CTX* ctx = EVP_CIPHER_CTX_new();
     if (!ctx) return false;
     int len = 0;
     int plaintext_len = 0;
     plaintext.resize(ciphertext.size());
     // Initialize decryption operation for AES-256-GCM
     bool ok = EVP_DecryptInit_ex(ctx, EVP_aes_256_gcm(), nullptr, nullptr, nullptr) == 1
         && EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_IVLEN, 12, nullptr) == 1
         && EVP_DecryptInit_ex(ctx, nullptr, nullptr, key, iv) == 1
         && EVP_DecryptUpdate(ctx, plaintext.data(), &len, ciphertext.data(), ciphertext.size()) == 1;
     plaintext_len = len;
     // Set expected authentication tag value
     ok = ok && EVP_CIPHER_CTX_ctrl(ctx, EVP_CTRL_GCM_SET_TAG, 16, (void*)tag) == 1;
     // Finalize decryption and check authentication
     int ret = EVP_DecryptFinal_ex(ctx, plaintext.data() + len, &len);
     EVP_CIPHER_CTX_free(ctx);
     if (!ok || ret <= 0) return false;
     plaintext.resize(plaintext_len);
     return true;
 }
Referenced by decrypt_ota_payload().
decrypt_ota_payload()
bool decrypt_ota_payload (const std::string & input, std::string & plaintext)
Decrypts an OTA (over-the-air) payload formatted as [IV|TAG|CIPHERTEXT]. Loads the AES key from file at runtime.
Decrypts an OTA (over-the-air) payload formatted as [IV|TAG|CIPHERTEXT].
Parameters
input The input string containing IV, tag, and ciphertext concatenated.
plaintext Output string for the decrypted data.
Returns
true on successful decryption and authentication, false otherwise.
Parameters
input The input string containing IV, tag, and ciphertext concatenated.
plaintext Output string for the decrypted data.
Returns
true on successful decryption and authentication, false otherwise.
Definition at line 82 of file aes_gcm_decrypt.cpp.
{
     // Check input size is sufficient for IV and tag
     if (input.size() < kAesIvLen + kAesTagLen) return false;
     // Extract IV, tag, and ciphertext from the input
     const unsigned char* iv = reinterpret_cast<const unsigned char*>(input.data());
     const unsigned char* tag = reinterpret_cast<const unsigned char*>(input.data()) + kAesIvLen;
     const unsigned char* ciphertext = reinterpret_cast<const unsigned char*>(input.data()) + kAesIvLen + kAesTagLen;
     size_t ciphertext_len = input.size() - kAesIvLen - kAesTagLen;
     std::vector<unsigned char> plain;
     std::vector<unsigned char> key;
     try {
         // Load AES key from file
         key = LoadAesKey();
     } catch (const std::exception& e) {
         return false;
     }
     // Perform AES-GCM decryption
     bool ok = aes_gcm_decrypt(
         std::vector<unsigned char>(ciphertext, ciphertext + ciphertext_len),
         key.data(),
         iv,
         tag,
         plain
     );
     if (ok) {
         plaintext.assign(plain.begin(), plain.end());
     }
     return ok;
 }
References aes_gcm_decrypt(), kAesIvLen, kAesTagLen, and LoadAesKey().
Referenced by JsonRequestExecutorHandler::Execute(), and ProtoRequestExecutorHandler::Execute().