Container Manager: containermanager::ContainerRequest Class Reference
containermanager::ContainerRequest Class Reference
#include <container_manager.pb.h>
Public Member Functions
ContainerRequest ()
virtual ~ContainerRequest ()
ContainerRequest (const ContainerRequest &from)
ContainerRequest & operator= (const ContainerRequest &from)
void Swap (ContainerRequest *other)
ContainerRequest * New () const final
ContainerRequest * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ContainerRequest &from)
void MergeFrom (const ContainerRequest &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
int parameters_size () const
void clear_parameters ()
::containermanager::ContainerParameters * mutable_parameters (int index)
::google::protobuf::RepeatedPtrField< ::containermanager::ContainerParameters > * mutable_parameters ()
const ::containermanager::ContainerParameters & parameters (int index) const
::containermanager::ContainerParameters * add_parameters ()
const ::google::protobuf::RepeatedPtrField< ::containermanager::ContainerParameters > & parameters () const
void clear_runtime ()
const ::std::string & runtime () const
void set_runtime (const ::std::string &value)
void set_runtime (const char *value)
void set_runtime (const char *value, size_t size)
::std::string * mutable_runtime ()
::std::string * release_runtime ()
void set_allocated_runtime (::std::string *runtime)
void clear_operation ()
const ::std::string & operation () const
void set_operation (const ::std::string &value)
void set_operation (const char *value)
void set_operation (const char *value, size_t size)
::std::string * mutable_operation ()
::std::string * release_operation ()
void set_allocated_operation (::std::string *operation)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const ContainerRequest & default_instance ()
static void InitAsDefaultInstance ()
static const ContainerRequest * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kParametersFieldNumber = 3
static const int kRuntimeFieldNumber = 1
static const int kOperationFieldNumber = 2
Friends
struct ::protobuf_container_5fmanager_2eproto::TableStruct
void swap (ContainerRequest &a, ContainerRequest &b)
Detailed Description
Definition at line 252 of file container_manager.pb.h.
Constructor & Destructor Documentation
ContainerRequest() [1/2]
ContainerRequest::ContainerRequest ()
Definition at line 696 of file container_manager.pb.cc.
   : ::google::protobuf::Message(), _internal_metadata_(NULL) {
   ::google::protobuf::internal::InitSCC(
       &protobuf_container_5fmanager_2eproto::scc_info_ContainerRequest.base);
   SharedCtor();
   // @@protoc_insertion_point(constructor:containermanager.ContainerRequest)
 }
References protobuf_container_5fmanager_2eproto::scc_info_ContainerRequest.
~ContainerRequest()
ContainerRequest::~ContainerRequest () virtual
Definition at line 724 of file container_manager.pb.cc.
{
   // @@protoc_insertion_point(destructor:containermanager.ContainerRequest)
   SharedDtor();
 }
ContainerRequest() [2/2]
ContainerRequest::ContainerRequest (const ContainerRequest & from)
Definition at line 703 of file container_manager.pb.cc.
   : ::google::protobuf::Message(),
       _internal_metadata_(NULL),
       parameters_(from.parameters_) {
   _internal_metadata_.MergeFrom(from._internal_metadata_);
   runtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.runtime().size() > 0) {
     runtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.runtime_);
   }
   operation_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.operation().size() > 0) {
     operation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operation_);
   }
   // @@protoc_insertion_point(copy_constructor:containermanager.ContainerRequest)
 }
References operation(), and runtime().
Member Function Documentation
add_parameters()
containermanager::ContainerParameters * ContainerRequest::add_parameters () inline
Definition at line 848 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_add:containermanager.ContainerRequest.parameters)
   return parameters_.Add();
 }
Referenced by MergePartialFromCodedStream().
ByteSizeLong()
size_t ContainerRequest::ByteSizeLong () const final
Definition at line 921 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:containermanager.ContainerRequest)
   size_t total_size = 0;
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
   }
   // repeated .containermanager.ContainerParameters parameters = 3;
   {
     unsigned int count = static_cast<unsigned int>(this->parameters_size());
     total_size += 1UL * count;
     for (unsigned int i = 0; i < count; i++) {
       total_size +=
         ::google::protobuf::internal::WireFormatLite::MessageSize(
           this->parameters(static_cast<int>(i)));
     }
   }
   // string runtime = 1;
   if (this->runtime().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->runtime());
   }
   // string operation = 2;
   if (this->operation().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->operation());
   }
   int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
   SetCachedSize(cached_size);
   return total_size;
 }
References operation(), parameters(), parameters_size(), and runtime().
Clear()
void ContainerRequest::Clear () final
Definition at line 748 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(message_clear_start:containermanager.ContainerRequest)
   ::google::protobuf::uint32 cached_has_bits = 0;
   // Prevent compiler warnings about cached_has_bits being unused
   (void) cached_has_bits;
   parameters_.Clear();
   runtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   operation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   _internal_metadata_.Clear();
 }
Referenced by CopyFrom().
clear_operation()
void ContainerRequest::clear_operation () inline
Definition at line 776 of file container_manager.pb.h.
{
   operation_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_parameters()
void ContainerRequest::clear_parameters () inline
Definition at line 832 of file container_manager.pb.h.
{
   parameters_.Clear();
 }
clear_runtime()
void ContainerRequest::clear_runtime () inline
Definition at line 723 of file container_manager.pb.h.
{
   runtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
CopyFrom() [1/2]
void ContainerRequest::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 993 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(generalized_copy_from_start:containermanager.ContainerRequest)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
References Clear(), and MergeFrom().
Referenced by operator=().
CopyFrom() [2/2]
void ContainerRequest::CopyFrom (const ContainerRequest & from)
Definition at line 1000 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(class_specific_copy_from_start:containermanager.ContainerRequest)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
References Clear(), and MergeFrom().
default_instance()
const ContainerRequest & ContainerRequest::default_instance () static
Definition at line 742 of file container_manager.pb.cc.
{
   ::google::protobuf::internal::InitSCC(&protobuf_container_5fmanager_2eproto::scc_info_ContainerRequest.base);
   return *internal_default_instance();
 }
References internal_default_instance(), and protobuf_container_5fmanager_2eproto::scc_info_ContainerRequest.
descriptor()
const ::google::protobuf::Descriptor * ContainerRequest::descriptor () static
Definition at line 737 of file container_manager.pb.cc.
{
   ::protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
   return ::protobuf_container_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
 }
References protobuf_container_5fmanager_2eproto::file_level_metadata, kIndexInFileMessages, and protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce().
GetCachedSize()
int containermanager::ContainerRequest::GetCachedSize () const inline final
Definition at line 317 of file container_manager.pb.h.
 { return _cached_size_.Get(); }
GetMetadata()
google::protobuf::Metadata ContainerRequest::GetMetadata () const final
Definition at line 1025 of file container_manager.pb.cc.
{
   protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
   return ::protobuf_container_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
 }
References protobuf_container_5fmanager_2eproto::file_level_metadata, kIndexInFileMessages, and protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce().
InitAsDefaultInstance()
void ContainerRequest::InitAsDefaultInstance () static
Definition at line 688 of file container_manager.pb.cc.
{
 }
internal_default_instance()
static const ContainerRequest* containermanager::ContainerRequest::internal_default_instance () inline static
Definition at line 282 of file container_manager.pb.h.
{
     return reinterpret_cast<const ContainerRequest*>(
                &_ContainerRequest_default_instance_);
   }
References containermanager::_ContainerRequest_default_instance_.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * ContainerRequest::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 876 of file container_manager.pb.cc.
{
   (void)deterministic; // Unused
   // @@protoc_insertion_point(serialize_to_array_start:containermanager.ContainerRequest)
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   // string runtime = 1;
   if (this->runtime().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->runtime().data(), static_cast<int>(this->runtime().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerRequest.runtime");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         1, this->runtime(), target);
   }
   // string operation = 2;
   if (this->operation().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->operation().data(), static_cast<int>(this->operation().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerRequest.operation");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         2, this->operation(), target);
   }
   // repeated .containermanager.ContainerParameters parameters = 3;
   for (unsigned int i = 0,
       n = static_cast<unsigned int>(this->parameters_size()); i < n; i++) {
     target = ::google::protobuf::internal::WireFormatLite::
       InternalWriteMessageToArray(
         3, this->parameters(static_cast<int>(i)), deterministic, target);
   }
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
   }
   // @@protoc_insertion_point(serialize_to_array_end:containermanager.ContainerRequest)
   return target;
 }
References operation(), parameters(), parameters_size(), and runtime().
IsInitialized()
bool ContainerRequest::IsInitialized () const final
Definition at line 1007 of file container_manager.pb.cc.
{
   return true;
 }
MergeFrom() [1/2]
void ContainerRequest::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 960 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(generalized_merge_from_start:containermanager.ContainerRequest)
   GOOGLE_DCHECK_NE(&from, this);
   const ContainerRequest* source =
       ::google::protobuf::internal::DynamicCastToGenerated<const ContainerRequest>(
           &from);
   if (source == NULL) {
   // @@protoc_insertion_point(generalized_merge_from_cast_fail:containermanager.ContainerRequest)
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
   // @@protoc_insertion_point(generalized_merge_from_cast_success:containermanager.ContainerRequest)
     MergeFrom(*source);
   }
 }
Referenced by CopyFrom().
MergeFrom() [2/2]
void ContainerRequest::MergeFrom (const ContainerRequest & from)
Definition at line 975 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(class_specific_merge_from_start:containermanager.ContainerRequest)
   GOOGLE_DCHECK_NE(&from, this);
   _internal_metadata_.MergeFrom(from._internal_metadata_);
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   parameters_.MergeFrom(from.parameters_);
   if (from.runtime().size() > 0) {
     runtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.runtime_);
   }
   if (from.operation().size() > 0) {
     operation_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operation_);
   }
 }
References operation(), and runtime().
MergePartialFromCodedStream()
bool ContainerRequest::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 760 of file container_manager.pb.cc.
{
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
   ::google::protobuf::uint32 tag;
   // @@protoc_insertion_point(parse_start:containermanager.ContainerRequest)
   for (;;) {
     ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
     tag = p.first;
     if (!p.second) goto handle_unusual;
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // string runtime = 1;
       case 1: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_runtime()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->runtime().data(), static_cast<int>(this->runtime().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerRequest.runtime"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string operation = 2;
       case 2: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_operation()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->operation().data(), static_cast<int>(this->operation().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerRequest.operation"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // repeated .containermanager.ContainerParameters parameters = 3;
       case 3: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                 input, add_parameters()));
         } else {
           goto handle_unusual;
         }
         break;
       }
       default: {
       handle_unusual:
         if (tag == 0) {
           goto success;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, _internal_metadata_.mutable_unknown_fields()));
         break;
       }
     }
   }
 success:
   // @@protoc_insertion_point(parse_success:containermanager.ContainerRequest)
   return true;
 failure:
   // @@protoc_insertion_point(parse_failure:containermanager.ContainerRequest)
   return false;
 #undef DO_
 }
References add_parameters(), DO_, mutable_operation(), mutable_runtime(), operation(), and runtime().
mutable_operation()
std::string * ContainerRequest::mutable_operation () inline
Definition at line 808 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerRequest.operation)
   return operation_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_parameters() [1/2]
google::protobuf::RepeatedPtrField<::containermanager::ContainerParameters > * ContainerRequest::mutable_parameters () inline
Definition at line 840 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable_list:containermanager.ContainerRequest.parameters)
   return &parameters_;
 }
mutable_parameters() [2/2]
containermanager::ContainerParameters * ContainerRequest::mutable_parameters (int index) inline
Definition at line 835 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerRequest.parameters)
   return parameters_.Mutable(index);
 }
mutable_runtime()
std::string * ContainerRequest::mutable_runtime () inline
Definition at line 755 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerRequest.runtime)
   return runtime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
New() [1/2]
ContainerRequest* containermanager::ContainerRequest::New () const inline final
Definition at line 296 of file container_manager.pb.h.
{
     return CreateMaybeMessage<ContainerRequest>(NULL);
   }
New() [2/2]
ContainerRequest* containermanager::ContainerRequest::New (::google::protobuf::Arena * arena) const inline final
Definition at line 300 of file container_manager.pb.h.
{
     return CreateMaybeMessage<ContainerRequest>(arena);
   }
operation()
const ::std::string & ContainerRequest::operation () const inline
Definition at line 779 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerRequest.operation)
   return operation_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerRequest(), ProtoRequestExecutorHandler::Execute(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_operation().
operator=()
ContainerRequest& containermanager::ContainerRequest::operator= (const ContainerRequest & from) inline
Definition at line 259 of file container_manager.pb.h.
{
     CopyFrom(from);
     return *this;
   }
References CopyFrom().
parameters() [1/2]
const ::google::protobuf::RepeatedPtrField<::containermanager::ContainerParameters > & ContainerRequest::parameters () const inline
Definition at line 853 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_list:containermanager.ContainerRequest.parameters)
   return parameters_;
 }
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
parameters() [2/2]
const ::containermanager::ContainerParameters & ContainerRequest::parameters (int index) const inline
Definition at line 844 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerRequest.parameters)
   return parameters_.Get(index);
 }
Referenced by ProtoRequestExecutorHandler::Execute().
parameters_size()
int ContainerRequest::parameters_size () const inline
Definition at line 829 of file container_manager.pb.h.
{
   return parameters_.size();
 }
Referenced by ByteSizeLong(), InternalSerializeWithCachedSizesToArray(), and SerializeWithCachedSizes().
release_operation()
std::string * ContainerRequest::release_operation () inline
Definition at line 813 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerRequest.operation)
   return operation_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_runtime()
std::string * ContainerRequest::release_runtime () inline
Definition at line 760 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerRequest.runtime)
   return runtime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
runtime()
const ::std::string & ContainerRequest::runtime () const inline
Definition at line 726 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerRequest.runtime)
   return runtime_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerRequest(), ProtoRequestExecutorHandler::Execute(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_runtime().
SerializeWithCachedSizes()
void ContainerRequest::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 834 of file container_manager.pb.cc.
{
   // @@protoc_insertion_point(serialize_start:containermanager.ContainerRequest)
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   // string runtime = 1;
   if (this->runtime().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->runtime().data(), static_cast<int>(this->runtime().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerRequest.runtime");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       1, this->runtime(), output);
   }
   // string operation = 2;
   if (this->operation().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->operation().data(), static_cast<int>(this->operation().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerRequest.operation");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       2, this->operation(), output);
   }
   // repeated .containermanager.ContainerParameters parameters = 3;
   for (unsigned int i = 0,
       n = static_cast<unsigned int>(this->parameters_size()); i < n; i++) {
     ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
       3,
       this->parameters(static_cast<int>(i)),
       output);
   }
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
   }
   // @@protoc_insertion_point(serialize_end:containermanager.ContainerRequest)
 }
References operation(), parameters(), parameters_size(), and runtime().
set_allocated_operation()
void ContainerRequest::set_allocated_operation (::std::string * operation) inline
Definition at line 818 of file container_manager.pb.h.
{
   if (operation != NULL) {
   } else {
   }
   operation_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), operation);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerRequest.operation)
 }
References operation().
set_allocated_runtime()
void ContainerRequest::set_allocated_runtime (::std::string * runtime) inline
Definition at line 765 of file container_manager.pb.h.
{
   if (runtime != NULL) {
   } else {
   }
   runtime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), runtime);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerRequest.runtime)
 }
References runtime().
set_operation() [1/3]
void ContainerRequest::set_operation (const ::std::string & value) inline
Definition at line 783 of file container_manager.pb.h.
{
   operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerRequest.operation)
 }
set_operation() [2/3]
void ContainerRequest::set_operation (const char * value) inline
Definition at line 796 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerRequest.operation)
 }
set_operation() [3/3]
void ContainerRequest::set_operation (const char * value, size_t size) inline
Definition at line 802 of file container_manager.pb.h.
{
   operation_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerRequest.operation)
 }
set_runtime() [1/3]
void ContainerRequest::set_runtime (const ::std::string & value) inline
Definition at line 730 of file container_manager.pb.h.
{
   runtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerRequest.runtime)
 }
set_runtime() [2/3]
void ContainerRequest::set_runtime (const char * value) inline
Definition at line 743 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   runtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerRequest.runtime)
 }
set_runtime() [3/3]
void ContainerRequest::set_runtime (const char * value, size_t size) inline
Definition at line 749 of file container_manager.pb.h.
{
   runtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerRequest.runtime)
 }
Swap()
void ContainerRequest::Swap (ContainerRequest * other)
Definition at line 1011 of file container_manager.pb.cc.
{
   if (other == this) return;
   InternalSwap(other);
 }
Friends And Related Function Documentation
::protobuf_container_5fmanager_2eproto::TableStruct
friend struct ::protobuf_container_5fmanager_2eproto::TableStruct friend
Definition at line 387 of file container_manager.pb.h.
swap
void swap (ContainerRequest & a, ContainerRequest & b) friend
Definition at line 290 of file container_manager.pb.h.
{
     a.Swap(&b);
   }
Member Data Documentation
kIndexInFileMessages
constexpr int containermanager::ContainerRequest::kIndexInFileMessages static constexpr
Initial value:
=
    1
Definition at line 286 of file container_manager.pb.h.
Referenced by descriptor(), and GetMetadata().
kOperationFieldNumber
const int ContainerRequest::kOperationFieldNumber = 2 static
Definition at line 367 of file container_manager.pb.h.
kParametersFieldNumber
const int ContainerRequest::kParametersFieldNumber = 3 static
Definition at line 342 of file container_manager.pb.h.
kRuntimeFieldNumber
const int ContainerRequest::kRuntimeFieldNumber = 1 static
Definition at line 353 of file container_manager.pb.h.
The documentation for this class was generated from the following files:
executor/proto/generated/container_manager.pb.h
executor/proto/generated/container_manager.pb.cc