Container Manager: PodmanApiRuntimeAvailableCommand Class Reference
PodmanApiRuntimeAvailableCommand Class Reference
Command to check if Podman daemon is available via the API.
#include <podman_api_commands.hpp>
Public Member Functions
PodmanApiRuntimeAvailableCommand ()
Constructs a PodmanApiRuntimeAvailableCommand.
~PodmanApiRuntimeAvailableCommand ()=default
Destructor.
Status Execute () const override
Executes the command to check Podman API runtime availability.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to check if Podman daemon is available via the API.
Definition at line 22 of file podman_api_commands.hpp.
Constructor & Destructor Documentation
PodmanApiRuntimeAvailableCommand()
PodmanApiRuntimeAvailableCommand::PodmanApiRuntimeAvailableCommand () explicit
Constructs a PodmanApiRuntimeAvailableCommand.
Definition at line 22 of file podman_api_commands.cpp.
 {}
~PodmanApiRuntimeAvailableCommand()
PodmanApiRuntimeAvailableCommand::~PodmanApiRuntimeAvailableCommand () default
Destructor.
Member Function Documentation
Execute()
Status PodmanApiRuntimeAvailableCommand::Execute () const override virtual
Executes the command to check Podman API runtime availability.
Returns
Status indicating if Podman is running.
Executes the command to check Podman API runtime availability.
Returns
Status indicating if Podman is running.
Implements Command.
Definition at line 26 of file podman_api_commands.cpp.
{
     CurlHandler curl;
     std::string response;
     std::string url = std::string(kPodmanApiBaseUrl) + std::string(ApiEndpoint::Ping);
     bool success = curl.GetUnix(url, kPodmanUnixSocketPath, response);
     if (success && response == "OK") {
         CM_LOG_INFO << "[Podman API] Podman daemon is running (/_ping returned OK)." << std::endl;
         return Status::Ok();
     } else if (success) {
         std::string msg = "[Podman API] Podman daemon responded, but not OK: " + response;
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::Unavailable, msg);
     } else {
         std::string msg = "[Podman API] Failed to contact Podman daemon.";
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::Unavailable, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, Status::Error(), CurlHandler::GetUnix(), kPodmanApiBaseUrl, kPodmanUnixSocketPath, Status::Ok(), ApiEndpoint::Ping, and Unavailable.
The documentation for this class was generated from the following files:
runtime/inc/podman_api_commands.hpp
runtime/src/podman_api_commands.cpp