Container Manager: RedisDatabaseHandler Class Reference
RedisDatabaseHandler Class Reference
Class for interacting with a Redis database backend.
#include <redis_database.hpp>
Public Member Functions
RedisDatabaseHandler ()
Constructs a RedisDatabaseHandler and connects to the Redis server.
~RedisDatabaseHandler ()
Destructor for RedisDatabaseHandler. Disconnects from the Redis server.
void SaveJson (const std::string &key, const nlohmann::json &value) override
Saves a JSON object to Redis with the specified key.
nlohmann::json GetJson (const std::string &key) override
Retrieves a JSON object from Redis by key.
void ClearDatabase () override
Clears all data from the Redis database.
void UpdateField (const std::string &key, const std::string &field, const std::string &value) override
Updates a specific field in the JSON object stored under the given key in Redis.
void RemoveKey (const std::string &key) override
Removes the JSON object associated with the specified key from Redis.
RedisDatabaseHandler (const RedisDatabaseHandler &)=delete
Deleted copy constructor to prevent copying.
RedisDatabaseHandler & operator= (const RedisDatabaseHandler &)=delete
Deleted copy assignment operator to prevent assignment.
Public Member Functions inherited from IDatabaseHandler
virtual ~IDatabaseHandler ()=default
Virtual destructor for safe polymorphic destruction.
Detailed Description
Class for interacting with a Redis database backend.
Implements the IDatabaseHandler interface for backend-agnostic database operations. Provides methods to save, retrieve, update, and remove JSON objects in Redis. Designed for direct instantiation and dependency injection.
Definition at line 23 of file redis_database.hpp.
Constructor & Destructor Documentation
RedisDatabaseHandler() [1/2]
RedisDatabaseHandler::RedisDatabaseHandler ()
Constructs a RedisDatabaseHandler and connects to the Redis server.
Definition at line 16 of file redis_database.cpp.
{
     // Connect to Redis server (adjust host/port as needed)
     redis_.connect();
 }
~RedisDatabaseHandler()
RedisDatabaseHandler::~RedisDatabaseHandler ()
Destructor for RedisDatabaseHandler. Disconnects from the Redis server.
Definition at line 24 of file redis_database.cpp.
{
     redis_.disconnect();
 }
RedisDatabaseHandler() [2/2]
RedisDatabaseHandler::RedisDatabaseHandler (const RedisDatabaseHandler &) delete
Deleted copy constructor to prevent copying.
Member Function Documentation
ClearDatabase()
void RedisDatabaseHandler::ClearDatabase () override virtual
Clears all data from the Redis database.
Implements IDatabaseHandler.
Definition at line 64 of file redis_database.cpp.
{
     redis_.flushdb();
     redis_.sync_commit();
 }
GetJson()
nlohmann::json RedisDatabaseHandler::GetJson (const std::string & key) override virtual
Retrieves a JSON object from Redis by key.
Parameters
key The key of the JSON object to retrieve.
Returns
The JSON object associated with the key, or an empty object if not found.
Implements IDatabaseHandler.
Definition at line 45 of file redis_database.cpp.
{
     try {
         auto reply = redis_.get(key);
         redis_.sync_commit();
         auto result = reply.get().as_string();
         if (result.empty()) {
             std::cerr << "[RedisDatabaseHandler] Key not found: " << key << std::endl;
             return nlohmann::json{}; // Return empty JSON object
         }
         return nlohmann::json::parse(result);
     } catch (const std::exception& e) {
         std::cerr << "[RedisDatabaseHandler] Error reading key " << key << ": " << e.what() << std::endl;
         return nlohmann::json{};
     }
 }
Referenced by UpdateField().
operator=()
RedisDatabaseHandler& RedisDatabaseHandler::operator= (const RedisDatabaseHandler &) delete
Deleted copy assignment operator to prevent assignment.
RemoveKey()
void RedisDatabaseHandler::RemoveKey (const std::string & key) override virtual
Removes the JSON object associated with the specified key from Redis.
Parameters
key The key of the JSON object to remove.
Implements IDatabaseHandler.
Definition at line 89 of file redis_database.cpp.
{
     redis_.del({key});
     redis_.sync_commit();
 }
SaveJson()
void RedisDatabaseHandler::SaveJson (const std::string & key, const nlohmann::json & value) override virtual
Saves a JSON object to Redis with the specified key.
Parameters
key The key under which the JSON object will be stored.
value The JSON object to store.
Implements IDatabaseHandler.
Definition at line 33 of file redis_database.cpp.
{
     // Save JSON as string
     std::string json_str = value.dump();
     redis_.set(key, json_str);
     redis_.sync_commit();
 }
Referenced by UpdateField().
UpdateField()
void RedisDatabaseHandler::UpdateField (const std::string & key, const std::string & field, const std::string & value) override virtual
Updates a specific field in the JSON object stored under the given key in Redis.
Parameters
key The key of the JSON object to update.
field The field within the JSON object to update.
value The new value for the specified field.
Implements IDatabaseHandler.
Definition at line 75 of file redis_database.cpp.
{
     nlohmann::json obj = GetJson(key);
     if (obj.is_null()) {
         std::cerr << "[RedisDatabaseHandler] Cannot update field, key not found: " << key << std::endl;
         return;
     }
     obj[field] = value;
     SaveJson(key, obj);
 }
References GetJson(), and SaveJson().
The documentation for this class was generated from the following files:
database/inc/redis_database.hpp
database/src/redis_database.cpp