Container Manager: CurlHandler Class Reference
CurlHandler Class Reference
CurlHandler provides simple HTTP methods over Unix domain sockets using libcurl.
#include <curl_handler.hpp>
Public Member Functions
CurlHandler ()
Construct a new CurlHandler object.
~CurlHandler ()
Destroy the CurlHandler object.
bool GetUnix (const std::string &url, const std::string &unix_socket, std::string &response)
Perform a HTTP GET request over a Unix domain socket.
bool PostUnix (const std::string &url, const std::string &unix_socket, const std::string &body, std::string &response, const std::string &content_type="application/json")
Perform a HTTP POST request over a Unix domain socket.
bool DeleteUnix (const std::string &url, const std::string &unix_socket, std::string &response)
Perform a HTTP DELETE request over a Unix domain socket.
Detailed Description
CurlHandler provides simple HTTP methods over Unix domain sockets using libcurl.
This class is designed to work with both Docker and Podman APIs, allowing you to send HTTP requests (GET, POST, DELETE) over a Unix socket.
Definition at line 10 of file curl_handler.hpp.
Constructor & Destructor Documentation
CurlHandler()
CurlHandler::CurlHandler ()
Construct a new CurlHandler object.
Default constructor for CurlHandler.
Definition at line 7 of file curl_handler.cpp.
 {}
~CurlHandler()
CurlHandler::~CurlHandler ()
Destroy the CurlHandler object.
Destructor for CurlHandler.
Definition at line 12 of file curl_handler.cpp.
 {}
Member Function Documentation
DeleteUnix()
bool CurlHandler::DeleteUnix (const std::string & url, const std::string & unix_socket, std::string & response)
Perform a HTTP DELETE request over a Unix domain socket.
Parameters
url The HTTP URL to request.
unix_socket The path to the Unix socket.
response Output parameter to store the response body.
Returns
true if the request was successful, false otherwise.
Definition at line 93 of file curl_handler.cpp.
{
     CURL* curl = curl_easy_init();
     if (!curl) return false;
     curl_easy_setopt(curl, CURLOPT_UNIX_SOCKET_PATH, unix_socket.c_str());
     curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
     curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "DELETE");
     curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
     curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
     CURLcode res = curl_easy_perform(curl);
     curl_easy_cleanup(curl);
     return (res == CURLE_OK);
 }
Referenced by DockerApiRemoveContainerCommand::Execute().
GetUnix()
bool CurlHandler::GetUnix (const std::string & url, const std::string & unix_socket, std::string & response)
Perform a HTTP GET request over a Unix domain socket.
Parameters
url The HTTP URL to request (e.g., http://localhost/_ping).
unix_socket The path to the Unix socket (e.g., /var/run/docker.sock).
response Output parameter to store the response body.
Returns
true if the request was successful, false otherwise.
Definition at line 38 of file curl_handler.cpp.
{
     CURL* curl = curl_easy_init();
     if (!curl) return false;
     curl_easy_setopt(curl, CURLOPT_UNIX_SOCKET_PATH, unix_socket.c_str());
     curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
     curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
     curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
     CURLcode res = curl_easy_perform(curl);
     curl_easy_cleanup(curl);
     return (res == CURLE_OK);
 }
Referenced by DockerApiRuntimeAvailableCommand::Execute(), and PodmanApiRuntimeAvailableCommand::Execute().
PostUnix()
bool CurlHandler::PostUnix (const std::string & url, const std::string & unix_socket, const std::string & body, std::string & response, const std::string & content_type = "application/json")
Perform a HTTP POST request over a Unix domain socket.
Parameters
url The HTTP URL to request.
unix_socket The path to the Unix socket.
body The request body to send (usually JSON).
response Output parameter to store the response body.
content_type The Content-Type header value (default: application/json).
Returns
true if the request was successful, false otherwise.
Definition at line 63 of file curl_handler.cpp.
{
     CURL* curl = curl_easy_init();
     if (!curl) return false;
     struct curl_slist* headers = nullptr;
     headers = curl_slist_append(headers, ("Content-Type: " + content_type).c_str());
     curl_easy_setopt(curl, CURLOPT_UNIX_SOCKET_PATH, unix_socket.c_str());
     curl_easy_setopt(curl, CURLOPT_URL, url.c_str());
     curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
     curl_easy_setopt(curl, CURLOPT_POST, 1L);
     curl_easy_setopt(curl, CURLOPT_POSTFIELDS, body.c_str());
     curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
     curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
     CURLcode res = curl_easy_perform(curl);
     curl_slist_free_all(headers);
     curl_easy_cleanup(curl);
     return (res == CURLE_OK);
 }
Referenced by DockerApiCreateContainerCommand::Execute(), PodmanApiCreateContainerCommand::Execute(), DockerApiStartContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), PodmanApiStopContainerCommand::Execute(), and DockerApiRestartContainerCommand::Execute().
The documentation for this class was generated from the following files:
utils/inc/curl_handler.hpp
utils/src/curl_handler.cpp