Container Manager: Invoker Class Reference
Invoker Class Reference
Invoker class to invoke the command.
#include <commands.hpp>
Public Member Functions
void SetCommand (std::unique_ptr< Command > cmd)
Set the command to be executed.
Status Invoke ()
Execute the command.
Detailed Description
Invoker class to invoke the command.
This class holds a command and invokes it. It manages the command's lifetime using a unique pointer.
Definition at line 42 of file commands.hpp.
Member Function Documentation
Invoke()
Status Invoker::Invoke () inline
Execute the command.
Returns
Status indicating the result of the command execution. Returns an error status if no command is set.
Definition at line 58 of file commands.hpp.
                     {
         if (command_) {
             return command_->Execute();
         }
         return Status(StatusCode::InvalidArgument, "No command set");
     }
References Command::Execute(), and InvalidArgument.
Referenced by ContainerServiceHandler::ContainerOperations().
SetCommand()
void Invoker::SetCommand (std::unique_ptr< Command > cmd) inline
Set the command to be executed.
Parameters
cmd Unique pointer to the command object.
Definition at line 50 of file commands.hpp.
{
         command_ = std::move(cmd);
     }
Referenced by ContainerServiceHandler::ContainerOperations().
The documentation for this class was generated from the following file:
runtime/inc/commands.hpp