Container Manager: DockerStopContainerCommand Class Reference
DockerStopContainerCommand Class Reference
Command to stop a Docker container.
#include <docker_commands.hpp>
Public Member Functions
DockerStopContainerCommand (const ContainerRequest &req)
Constructs a DockerStopContainerCommand.
~DockerStopContainerCommand ()=default
Destructor.
Status Execute () const override
Executes the command to stop a Docker container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to stop a Docker container.
Parameters
req The container request containing the container name.
Definition at line 96 of file docker_commands.hpp.
Constructor & Destructor Documentation
DockerStopContainerCommand()
DockerStopContainerCommand::DockerStopContainerCommand (const ContainerRequest & req) explicit
Constructs a DockerStopContainerCommand.
Parameters
req The container request containing the container name.
Definition at line 100 of file docker_commands.cpp.
 : req_(req) {}
~DockerStopContainerCommand()
DockerStopContainerCommand::~DockerStopContainerCommand () default
Destructor.
Member Function Documentation
Execute()
Status DockerStopContainerCommand::Execute () const override virtual
Executes the command to stop a Docker container.
Returns
Status indicating if the container was stopped successfully.
Executes the command to stop a Docker container.
Returns
Status indicating if the container was stopped successfully.
Implements Command.
Definition at line 104 of file docker_commands.cpp.
{
     std::string command = FormatCommand(
         CommandTemplate::Stop,
         {{"runtime", "docker"}, {"name", req_.container_name}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Docker container stopped successfully" << std::endl;
         return Status::Ok();
     } else {
         std::string msg = "Failed to stop Docker container, exit code: " + std::to_string(status);
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::InternalError, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, ContainerRequest::container_name, Status::Error(), FormatCommand(), InternalError, Status::Ok(), and CommandTemplate::Stop.
The documentation for this class was generated from the following files:
runtime/inc/docker_commands.hpp
runtime/src/docker_commands.cpp