Container Manager: ContainerServiceHandler Class Reference
ContainerServiceHandler Class Reference
Provides static methods for handling container operations and runtime checks.
#include <container_service.hpp>
Static Public Member Functions
static nlohmann::json HandleRequest (const ContainerRequest &req)
Handles a container request by dispatching to the appropriate operation.
static bool CheckRuntimeAvailable (const std::string &runtime, const std::string &operation)
Checks if the specified container runtime is available for the given operation.
static bool ContainerOperations (const std::string &runtime, const std::string &operation, const std::string &container_name)
Performs the specified container operation.
Detailed Description
Provides static methods for handling container operations and runtime checks.
This class acts as a service layer, coordinating container lifecycle operations and runtime status checks.
Definition at line 14 of file container_service.hpp.
Member Function Documentation
CheckRuntimeAvailable()
bool ContainerServiceHandler::CheckRuntimeAvailable (const std::string & runtime, const std::string & operation) static
Checks if the specified container runtime is available for the given operation.
Parameters
runtime The container runtime (e.g., "docker", "podman").
operation The operation to check runtime available.
Returns
True if the runtime is available, false otherwise.
Definition at line 57 of file container_service.cpp.
{
     Invoker invoker;
     invoker.SetCommand(CommandFactory::CreateCommand(runtime, operation));
         if (!invoker.Invoke()) {
             return false;
         }
     return true;
 }
References CommandFactory::CreateCommand(), Invoker::Invoke(), and Invoker::SetCommand().
Referenced by HandleRequest().
ContainerOperations()
bool ContainerServiceHandler::ContainerOperations (const std::string & runtime, const std::string & operation, const std::string & container_name) static
Performs the specified container operation.
Parameters
runtime The container runtime (e.g., "docker", "podman").
operation The operation to perform (e.g., "create", "start", "stop").
container_name The name of the container to operate on.
Returns
True if the operation succeeded, false otherwise.
Definition at line 67 of file container_service.cpp.
{
     Invoker invoker;
     invoker.SetCommand(CommandFactory::CreateCommand(runtime, operation, container_name));
     if (!invoker.Invoke()) {
         return false;
     }
     return true;
 }
References CommandFactory::CreateCommand(), Invoker::Invoke(), and Invoker::SetCommand().
Referenced by HandleRequest().
HandleRequest()
nlohmann::json ContainerServiceHandler::HandleRequest (const ContainerRequest & req) static
Handles a container request by dispatching to the appropriate operation.
Parameters
req The container request containing operation, runtime, and container details.
Returns
A JSON object with the result of the operation.
Definition at line 15 of file container_service.cpp.
{
     if(req.operation == CommandName::RuntimeStatus) {
         bool isRuntimeAvailable = ContainerServiceHandler::CheckRuntimeAvailable(req.runtime, req.operation);
         if (!isRuntimeAvailable) {
             return {{"status", "error"}, {"message", "Runtime is not running"}};
         }
     } else if (req.operation == CommandName::CreateContainer) {
         bool isContainerCreated = ContainerServiceHandler::ContainerOperations(req.runtime, req.operation, req.container_name);
         if (!isContainerCreated) {
             return {{"status", "error"}, {"message", "Failed to create container"}};
         }
     } else if (req.operation == CommandName::StartContainer) {
         // Start the container
         bool isContainerStarted = ContainerServiceHandler::ContainerOperations(req.runtime, req.operation, req.container_name);
         if (!isContainerStarted) {
             return {{"status", "error"}, {"message", "Failed to start container"}};
         }
     } else if (req.operation == CommandName::StopContainer) {
         // Stop the container
         bool isContainerStopped = ContainerServiceHandler::ContainerOperations(req.runtime, req.operation, req.container_name);
         if (!isContainerStopped) {
             return {{"status", "error"}, {"message", "Failed to stop container"}};
         }
     } else if (req.operation == CommandName::RestartContainer) {
         // Stop the container
         bool isContainerRestarted = ContainerServiceHandler::ContainerOperations(req.runtime, req.operation, req.container_name);
         if (!isContainerRestarted) {
             return {{"status", "error"}, {"message", "Failed to restart container"}};
         }
     } else if (req.operation == CommandName::RemoveContainer) {
         // Stop the container
         bool isContainerRemoved = ContainerServiceHandler::ContainerOperations(req.runtime, req.operation, req.container_name);
         if (!isContainerRemoved) {
             return {{"status", "error"}, {"message", "Failed to remove container"}};
         }
     } else {
         return {{"status", "error"}, {"message", "Invalid operation"}};
     }
     // TODO: Integrate with your command pattern and actual logic
     return {{"status", "success"}, {"operation", req.operation}, {"container", req.container_name}};
 }
References CheckRuntimeAvailable(), ContainerRequest::container_name, ContainerOperations(), CommandName::CreateContainer, ContainerRequest::operation, CommandName::RemoveContainer, CommandName::RestartContainer, ContainerRequest::runtime, CommandName::RuntimeStatus, CommandName::StartContainer, and CommandName::StopContainer.
Referenced by JsonRequestExecutorHandler::Execute().
The documentation for this class was generated from the following files:
core/inc/container_service.hpp
core/src/container_service.cpp