Container Manager: PodmanCreateContainerCommand Class Reference
PodmanCreateContainerCommand Class Reference
Command to create a Podman container with specified parameters.
#include <podman_commands.hpp>
Public Member Functions
PodmanCreateContainerCommand (const std::string &container_name_)
Constructs a PodmanCreateContainerCommand.
~PodmanCreateContainerCommand ()=default
Destructor.
bool Execute () const override
Executes the command to create a Podman container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Destructor.
Detailed Description
Command to create a Podman container with specified parameters.
Definition at line 38 of file podman_commands.hpp.
Constructor & Destructor Documentation
PodmanCreateContainerCommand()
PodmanCreateContainerCommand::PodmanCreateContainerCommand (const std::string & container_name_) explicit
Constructs a PodmanCreateContainerCommand.
Parameters
container_name_ Name of the container to create.
Definition at line 32 of file podman_commands.cpp.
                                                                                           : container_name_(container_name) {
     // Empty constructor
 }
~PodmanCreateContainerCommand()
PodmanCreateContainerCommand::~PodmanCreateContainerCommand () default
Destructor.
Member Function Documentation
Execute()
bool PodmanCreateContainerCommand::Execute () const override virtual
Executes the command to create a Podman container.
Returns
True if the container was created successfully, false otherwise.
Implements Command.
Definition at line 36 of file podman_commands.cpp.
{
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     nlohmann::json config = db.GetJson(container_name_);
     std::string image_name_;
     if (!config["parameters"].empty() && config["parameters"][0].contains("image_name")) {
         image_name_ = config["parameters"][0]["image_name"].get<std::string>();
     } else {
         image_name_ = "";
     }
     // Start the Podman container
     std::string command = "podman create --name " + container_name_ + " " + image_name_;
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Podman container created successfully";
         db.UpdateField(container_name_, "status", "created");
         return true;
     } else {
         CM_LOG_ERROR << "Failed to create Podman container";
         db.UpdateField(container_name_, "status", "Error creating container");
         return false;
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, RedisDatabaseHandler::GetInstance(), IDatabaseHandler::GetJson(), and IDatabaseHandler::UpdateField().
The documentation for this class was generated from the following files:
runtime/inc/podman_commands.hpp
runtime/src/podman_commands.cpp