Container Manager: MessageQueueConsumer Class Reference
MessageQueueConsumer Class Reference
Consumes messages from a POSIX message queue and dispatches them to a RequestExecutor.
#include <posix_message_queue_consumer.hpp>
Public Member Functions
MessageQueueConsumer (const MessageQueueConfig &config, std::shared_ptr< RequestExecutor > executor)
Constructs a MessageQueueConsumer.
~MessageQueueConsumer ()
Destructor.
void Start ()
Starts the message queue consumer loop in a separate thread.
void Stop ()
Stops the message queue consumer loop.
Detailed Description
Consumes messages from a POSIX message queue and dispatches them to a RequestExecutor.
Definition at line 17 of file posix_message_queue_consumer.hpp.
Constructor & Destructor Documentation
MessageQueueConsumer()
MessageQueueConsumer::MessageQueueConsumer (const MessageQueueConfig & config, std::shared_ptr< RequestExecutor > executor)
Constructs a MessageQueueConsumer.
Parameters
config Configuration for the message queue consumer.
executor Shared pointer to a RequestExecutor for processing messages.
Definition at line 17 of file posix_message_queue_consumer.cpp.
     : config_(config), executor_(std::move(executor)), running_(false) {}
~MessageQueueConsumer()
MessageQueueConsumer::~MessageQueueConsumer ()
Destructor.
Definition at line 20 of file posix_message_queue_consumer.cpp.
{
     Stop();
 }
References Stop().
Member Function Documentation
Start()
void MessageQueueConsumer::Start ()
Starts the message queue consumer loop in a separate thread.
Definition at line 24 of file posix_message_queue_consumer.cpp.
{
     running_ = true;
     consumer_thread_ = std::thread(&MessageQueueConsumer::ConsumeLoop, this);
 }
Referenced by main().
Stop()
void MessageQueueConsumer::Stop ()
Stops the message queue consumer loop.
Definition at line 29 of file posix_message_queue_consumer.cpp.
{
     running_ = false;
     if (consumer_thread_.joinable()) {
         consumer_thread_.join();
     }
 }
Referenced by main(), and ~MessageQueueConsumer().
The documentation for this class was generated from the following files:
api/inc/posix_message_queue_consumer.hpp
api/src/posix_message_queue_consumer.cpp