Container Manager: DockerStartContainerCommand Class Reference
DockerStartContainerCommand Class Reference
Command to start a Docker container.
#include <docker_commands.hpp>
Public Member Functions
DockerStartContainerCommand (const std::string &container_name_)
Constructs a DockerStartContainerCommand.
~DockerStartContainerCommand ()=default
Destructor.
bool Execute () const override
Executes the command to start a Docker container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Destructor.
Detailed Description
Command to start a Docker container.
Definition at line 61 of file docker_commands.hpp.
Constructor & Destructor Documentation
DockerStartContainerCommand()
DockerStartContainerCommand::DockerStartContainerCommand (const std::string & container_name_) explicit
Constructs a DockerStartContainerCommand.
Parameters
container_name_ Name of the container to start.
Definition at line 51 of file docker_commands.cpp.
                                                                                         : container_name_(container_name) {
     // Empty constructor
 }
~DockerStartContainerCommand()
DockerStartContainerCommand::~DockerStartContainerCommand () default
Destructor.
Member Function Documentation
Execute()
bool DockerStartContainerCommand::Execute () const override virtual
Executes the command to start a Docker container.
Returns
True if the container was started successfully, false otherwise.
Implements Command.
Definition at line 55 of file docker_commands.cpp.
{
     // Start the Docker container
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     std::string command = FormatCommand(
         CommandTemplate::Start,
         {{"runtime", "docker"}, {"name", container_name_}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Docker container started successfully";
         db.UpdateField(container_name_, "status", "running");
         return true;
     } else {
         CM_LOG_ERROR << "Failed to start Docker container";
         db.UpdateField(container_name_, "status", "Error running container");
         return false;
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, FormatCommand(), RedisDatabaseHandler::GetInstance(), CommandTemplate::Start, and IDatabaseHandler::UpdateField().
The documentation for this class was generated from the following files:
runtime/inc/docker_commands.hpp
runtime/src/docker_commands.cpp