Container Manager: DockerApiCreateContainerCommand Class Reference
DockerApiCreateContainerCommand Class Reference
Command to create a Docker container via the Docker API.
#include <docker_api_commands.hpp>
Public Member Functions
DockerApiCreateContainerCommand (const ContainerRequest &req)
Constructs a DockerApiCreateContainerCommand.
~DockerApiCreateContainerCommand ()=default
Destructor.
Status Execute () const override
Executes the command to create a Docker container via the API.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to create a Docker container via the Docker API.
Parameters
req The container request containing all parameters for creation.
Definition at line 45 of file docker_api_commands.hpp.
Constructor & Destructor Documentation
DockerApiCreateContainerCommand()
DockerApiCreateContainerCommand::DockerApiCreateContainerCommand (const ContainerRequest & req) explicit
Constructs a DockerApiCreateContainerCommand.
Parameters
req The container request containing all parameters for creation.
Definition at line 51 of file docker_api_commands.cpp.
 : req_(req) {}
~DockerApiCreateContainerCommand()
DockerApiCreateContainerCommand::~DockerApiCreateContainerCommand () default
Destructor.
Member Function Documentation
Execute()
Status DockerApiCreateContainerCommand::Execute () const override virtual
Executes the command to create a Docker container via the API.
Returns
Status indicating if the container was created successfully.
Executes the command to create a Docker container via the API.
Returns
Status indicating if the container was created successfully.
Implements Command.
Definition at line 55 of file docker_api_commands.cpp.
{
     CurlHandler curl;
     std::string response;
     std::string url = std::string(kDockerApiBaseUrl) +
                       std::string(ApiEndpoint::Create) +
                       req_.container_name;
     // Build JSON body with all relevant fields
     std::string body = "{";
     body += "\"Image\": \"" + req_.image_name + "\"";
     bool hasHostConfig = false;
     if (!req_.cpus.empty()) {
         body += ", \"HostConfig\": {\"NanoCpus\": " + std::to_string(static_cast<long long>(std::stod(req_.cpus) * 1e9));
         hasHostConfig = true;
     }
     if (!req_.memory.empty()) {
         if (!hasHostConfig) {
             body += ", \"HostConfig\": {";
             hasHostConfig = true;
         } else {
             body += ", ";
         }
         body += "\"Memory\": " + std::to_string(std::stoll(req_.memory) * 1024 * 1024);
     }
     if (!req_.pids.empty()) {
         if (!hasHostConfig) {
             body += ", \"HostConfig\": {";
             hasHostConfig = true;
         } else {
             body += ", ";
         }
         body += "\"PidsLimit\": " + req_.pids;
     }
     if (!req_.restart_policy.empty()) {
         if (!hasHostConfig) {
             body += ", \"HostConfig\": {";
             hasHostConfig = true;
         } else {
             body += ", ";
         }
         body += "\"RestartPolicy\": {\"Name\": \"" + req_.restart_policy + "\"}";
     }
     if (hasHostConfig)
         body += "}";
     body += "}";
     bool success = curl.PostUnix(url, kDockerUnixSocketPath, body, response);
     if (success) {
         CM_LOG_INFO << "[Docker API] Create container response: " << response;
         return Status::Ok();
     } else {
         std::string msg = "[Docker API] Failed to create container. Response: " + response;
         CM_LOG_ERROR << msg;
         return Status::Error(StatusCode::InternalError, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, ContainerRequest::container_name, ContainerRequest::cpus, ApiEndpoint::Create, Status::Error(), ContainerRequest::image_name, InternalError, kDockerApiBaseUrl, kDockerUnixSocketPath, ContainerRequest::memory, Status::Ok(), ContainerRequest::pids, CurlHandler::PostUnix(), and ContainerRequest::restart_policy.
The documentation for this class was generated from the following files:
runtime/inc/docker_api_commands.hpp
runtime/src/docker_api_commands.cpp