Container Manager: containermanager::ContainerParameters Class Reference
containermanager::ContainerParameters Class Reference
#include <container_manager.pb.h>
Public Member Functions
ContainerParameters ()
virtual ~ContainerParameters ()
ContainerParameters (const ContainerParameters &from)
ContainerParameters & operator= (const ContainerParameters &from)
void Swap (ContainerParameters *other)
ContainerParameters * New () const final
ContainerParameters * New (::google::protobuf::Arena *arena) const final
void CopyFrom (const ::google::protobuf::Message &from) final
void MergeFrom (const ::google::protobuf::Message &from) final
void CopyFrom (const ContainerParameters &from)
void MergeFrom (const ContainerParameters &from)
void Clear () final
bool IsInitialized () const final
size_t ByteSizeLong () const final
bool MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream *input) final
void SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream *output) const final
::google::protobuf::uint8 * InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 *target) const final
int GetCachedSize () const final
::google::protobuf::Metadata GetMetadata () const final
void clear_container_name ()
const ::std::string & container_name () const
void set_container_name (const ::std::string &value)
void set_container_name (const char *value)
void set_container_name (const char *value, size_t size)
::std::string * mutable_container_name ()
::std::string * release_container_name ()
void set_allocated_container_name (::std::string *container_name)
void clear_cpus ()
const ::std::string & cpus () const
void set_cpus (const ::std::string &value)
void set_cpus (const char *value)
void set_cpus (const char *value, size_t size)
::std::string * mutable_cpus ()
::std::string * release_cpus ()
void set_allocated_cpus (::std::string *cpus)
void clear_memory ()
const ::std::string & memory () const
void set_memory (const ::std::string &value)
void set_memory (const char *value)
void set_memory (const char *value, size_t size)
::std::string * mutable_memory ()
::std::string * release_memory ()
void set_allocated_memory (::std::string *memory)
void clear_pids ()
const ::std::string & pids () const
void set_pids (const ::std::string &value)
void set_pids (const char *value)
void set_pids (const char *value, size_t size)
::std::string * mutable_pids ()
::std::string * release_pids ()
void set_allocated_pids (::std::string *pids)
void clear_restart_policy ()
const ::std::string & restart_policy () const
void set_restart_policy (const ::std::string &value)
void set_restart_policy (const char *value)
void set_restart_policy (const char *value, size_t size)
::std::string * mutable_restart_policy ()
::std::string * release_restart_policy ()
void set_allocated_restart_policy (::std::string *restart_policy)
void clear_image_name ()
const ::std::string & image_name () const
void set_image_name (const ::std::string &value)
void set_image_name (const char *value)
void set_image_name (const char *value, size_t size)
::std::string * mutable_image_name ()
::std::string * release_image_name ()
void set_allocated_image_name (::std::string *image_name)
Static Public Member Functions
static const ::google::protobuf::Descriptor * descriptor ()
static const ContainerParameters & default_instance ()
static void InitAsDefaultInstance ()
static const ContainerParameters * internal_default_instance ()
Static Public Attributes
static constexpr int kIndexInFileMessages
static const int kContainerNameFieldNumber = 1
static const int kCpusFieldNumber = 2
static const int kMemoryFieldNumber = 3
static const int kPidsFieldNumber = 4
static const int kRestartPolicyFieldNumber = 5
static const int kImageNameFieldNumber = 6
Friends
struct ::protobuf_container_5fmanager_2eproto::TableStruct
void swap (ContainerParameters &a, ContainerParameters &b)
Detailed Description
Definition at line 66 of file container_manager.pb.h.
Constructor & Destructor Documentation
ContainerParameters() [1/2]
containermanager::ContainerParameters::ContainerParameters ()
Definition at line 167 of file container_manager.pb.cc.
   : ::google::protobuf::Message(), _internal_metadata_(NULL) {
   ::google::protobuf::internal::InitSCC(
       &protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters.base);
   SharedCtor();
   // @@protoc_insertion_point(constructor:containermanager.ContainerParameters)
 }
References protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters.
~ContainerParameters()
containermanager::ContainerParameters::~ContainerParameters () virtual
Definition at line 214 of file container_manager.pb.cc.
{
   // @@protoc_insertion_point(destructor:containermanager.ContainerParameters)
   SharedDtor();
 }
ContainerParameters() [2/2]
containermanager::ContainerParameters::ContainerParameters (const ContainerParameters & from)
Definition at line 174 of file container_manager.pb.cc.
   : ::google::protobuf::Message(),
       _internal_metadata_(NULL) {
   _internal_metadata_.MergeFrom(from._internal_metadata_);
   container_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.container_name().size() > 0) {
     container_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.container_name_);
   }
   cpus_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.cpus().size() > 0) {
     cpus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cpus_);
   }
   memory_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.memory().size() > 0) {
     memory_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.memory_);
   }
   pids_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.pids().size() > 0) {
     pids_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pids_);
   }
   restart_policy_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.restart_policy().size() > 0) {
     restart_policy_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.restart_policy_);
   }
   image_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   if (from.image_name().size() > 0) {
     image_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.image_name_);
   }
   // @@protoc_insertion_point(copy_constructor:containermanager.ContainerParameters)
 }
References container_name(), cpus(), image_name(), memory(), pids(), and restart_policy().
Member Function Documentation
ByteSizeLong()
size_t containermanager::ContainerParameters::ByteSizeLong () const final
Definition at line 537 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(message_byte_size_start:containermanager.ContainerParameters)
   size_t total_size = 0;
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     total_size +=
       ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
   }
   // string container_name = 1;
   if (this->container_name().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->container_name());
   }
   // string cpus = 2;
   if (this->cpus().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->cpus());
   }
   // string memory = 3;
   if (this->memory().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->memory());
   }
   // string pids = 4;
   if (this->pids().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->pids());
   }
   // string restart_policy = 5;
   if (this->restart_policy().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->restart_policy());
   }
   // string image_name = 6;
   if (this->image_name().size() > 0) {
     total_size += 1 +
       ::google::protobuf::internal::WireFormatLite::StringSize(
         this->image_name());
   }
   int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
   SetCachedSize(cached_size);
   return total_size;
 }
References container_name(), cpus(), image_name(), memory(), pids(), and restart_policy().
Clear()
void containermanager::ContainerParameters::Clear () final
Definition at line 242 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(message_clear_start:containermanager.ContainerParameters)
   ::google::protobuf::uint32 cached_has_bits = 0;
   // Prevent compiler warnings about cached_has_bits being unused
   (void) cached_has_bits;
   container_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   cpus_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   memory_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   pids_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   restart_policy_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   image_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
   _internal_metadata_.Clear();
 }
Referenced by CopyFrom().
clear_container_name()
void containermanager::ContainerParameters::clear_container_name () inline
Definition at line 401 of file container_manager.pb.h.
{
   container_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_cpus()
void containermanager::ContainerParameters::clear_cpus () inline
Definition at line 454 of file container_manager.pb.h.
{
   cpus_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_image_name()
void containermanager::ContainerParameters::clear_image_name () inline
Definition at line 666 of file container_manager.pb.h.
{
   image_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_memory()
void containermanager::ContainerParameters::clear_memory () inline
Definition at line 507 of file container_manager.pb.h.
{
   memory_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_pids()
void containermanager::ContainerParameters::clear_pids () inline
Definition at line 560 of file container_manager.pb.h.
{
   pids_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
clear_restart_policy()
void containermanager::ContainerParameters::clear_restart_policy () inline
Definition at line 613 of file container_manager.pb.h.
{
   restart_policy_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
container_name()
const ::std::string & containermanager::ContainerParameters::container_name () const inline
Definition at line 404 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.container_name)
   return container_name_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), ProtoRequestExecutorHandler::Execute(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_container_name().
CopyFrom() [1/2]
void containermanager::ContainerParameters::CopyFrom (const ::google::protobuf::Message & from) final
Definition at line 641 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(generalized_copy_from_start:containermanager.ContainerParameters)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
References Clear(), and MergeFrom().
Referenced by operator=().
CopyFrom() [2/2]
void containermanager::ContainerParameters::CopyFrom (const ContainerParameters & from)
Definition at line 648 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(class_specific_copy_from_start:containermanager.ContainerParameters)
   if (&from == this) return;
   Clear();
   MergeFrom(from);
 }
References Clear(), and MergeFrom().
cpus()
const ::std::string & containermanager::ContainerParameters::cpus () const inline
Definition at line 457 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.cpus)
   return cpus_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_cpus().
default_instance()
const ContainerParameters & containermanager::ContainerParameters::default_instance () static
Definition at line 236 of file container_manager.pb.cc.
{
   ::google::protobuf::internal::InitSCC(&protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters.base);
   return *internal_default_instance();
 }
References internal_default_instance(), and protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters.
descriptor()
const ::google::protobuf::Descriptor * containermanager::ContainerParameters::descriptor () static
Definition at line 231 of file container_manager.pb.cc.
{
   ::protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
   return ::protobuf_container_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
 }
References protobuf_container_5fmanager_2eproto::file_level_metadata, kIndexInFileMessages, and protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce().
GetCachedSize()
int containermanager::ContainerParameters::GetCachedSize () const inline final
Definition at line 131 of file container_manager.pb.h.
 { return _cached_size_.Get(); }
GetMetadata()
google::protobuf::Metadata containermanager::ContainerParameters::GetMetadata () const final
Definition at line 680 of file container_manager.pb.cc.
{
   protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce();
   return ::protobuf_container_5fmanager_2eproto::file_level_metadata[kIndexInFileMessages];
 }
References protobuf_container_5fmanager_2eproto::file_level_metadata, kIndexInFileMessages, and protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce().
image_name()
const ::std::string & containermanager::ContainerParameters::image_name () const inline
Definition at line 669 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.image_name)
   return image_name_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_image_name().
InitAsDefaultInstance()
void containermanager::ContainerParameters::InitAsDefaultInstance () static
Definition at line 156 of file container_manager.pb.cc.
{
 }
internal_default_instance()
static const ContainerParameters* containermanager::ContainerParameters::internal_default_instance () inline static
Definition at line 96 of file container_manager.pb.h.
{
     return reinterpret_cast<const ContainerParameters*>(
                &_ContainerParameters_default_instance_);
   }
References containermanager::_ContainerParameters_default_instance_.
Referenced by default_instance().
InternalSerializeWithCachedSizesToArray()
google::protobuf::uint8 * containermanager::ContainerParameters::InternalSerializeWithCachedSizesToArray (bool deterministic, ::google::protobuf::uint8 * target) const final
Definition at line 456 of file container_manager.pb.cc.
{
   (void)deterministic; // Unused
   // @@protoc_insertion_point(serialize_to_array_start:containermanager.ContainerParameters)
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   // string container_name = 1;
   if (this->container_name().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->container_name().data(), static_cast<int>(this->container_name().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.container_name");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         1, this->container_name(), target);
   }
   // string cpus = 2;
   if (this->cpus().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->cpus().data(), static_cast<int>(this->cpus().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.cpus");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         2, this->cpus(), target);
   }
   // string memory = 3;
   if (this->memory().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->memory().data(), static_cast<int>(this->memory().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.memory");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         3, this->memory(), target);
   }
   // string pids = 4;
   if (this->pids().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->pids().data(), static_cast<int>(this->pids().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.pids");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         4, this->pids(), target);
   }
   // string restart_policy = 5;
   if (this->restart_policy().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->restart_policy().data(), static_cast<int>(this->restart_policy().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.restart_policy");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         5, this->restart_policy(), target);
   }
   // string image_name = 6;
   if (this->image_name().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->image_name().data(), static_cast<int>(this->image_name().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.image_name");
     target =
       ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
         6, this->image_name(), target);
   }
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
   }
   // @@protoc_insertion_point(serialize_to_array_end:containermanager.ContainerParameters)
   return target;
 }
References container_name(), cpus(), image_name(), memory(), pids(), and restart_policy().
IsInitialized()
bool containermanager::ContainerParameters::IsInitialized () const final
Definition at line 655 of file container_manager.pb.cc.
{
   return true;
 }
memory()
const ::std::string & containermanager::ContainerParameters::memory () const inline
Definition at line 510 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.memory)
   return memory_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_memory().
MergeFrom() [1/2]
void containermanager::ContainerParameters::MergeFrom (const ::google::protobuf::Message & from) final
Definition at line 593 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(generalized_merge_from_start:containermanager.ContainerParameters)
   GOOGLE_DCHECK_NE(&from, this);
   const ContainerParameters* source =
       ::google::protobuf::internal::DynamicCastToGenerated<const ContainerParameters>(
           &from);
   if (source == NULL) {
   // @@protoc_insertion_point(generalized_merge_from_cast_fail:containermanager.ContainerParameters)
     ::google::protobuf::internal::ReflectionOps::Merge(from, this);
   } else {
   // @@protoc_insertion_point(generalized_merge_from_cast_success:containermanager.ContainerParameters)
     MergeFrom(*source);
   }
 }
Referenced by CopyFrom().
MergeFrom() [2/2]
void containermanager::ContainerParameters::MergeFrom (const ContainerParameters & from)
Definition at line 608 of file container_manager.pb.cc.
{
 // @@protoc_insertion_point(class_specific_merge_from_start:containermanager.ContainerParameters)
   GOOGLE_DCHECK_NE(&from, this);
   _internal_metadata_.MergeFrom(from._internal_metadata_);
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   if (from.container_name().size() > 0) {
     container_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.container_name_);
   }
   if (from.cpus().size() > 0) {
     cpus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cpus_);
   }
   if (from.memory().size() > 0) {
     memory_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.memory_);
   }
   if (from.pids().size() > 0) {
     pids_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pids_);
   }
   if (from.restart_policy().size() > 0) {
     restart_policy_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.restart_policy_);
   }
   if (from.image_name().size() > 0) {
     image_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.image_name_);
   }
 }
References container_name(), cpus(), image_name(), memory(), pids(), and restart_policy().
MergePartialFromCodedStream()
bool containermanager::ContainerParameters::MergePartialFromCodedStream (::google::protobuf::io::CodedInputStream * input) final
Definition at line 257 of file container_manager.pb.cc.
{
 #define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
   ::google::protobuf::uint32 tag;
   // @@protoc_insertion_point(parse_start:containermanager.ContainerParameters)
   for (;;) {
     ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
     tag = p.first;
     if (!p.second) goto handle_unusual;
     switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
       // string container_name = 1;
       case 1: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_container_name()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->container_name().data(), static_cast<int>(this->container_name().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.container_name"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string cpus = 2;
       case 2: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_cpus()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->cpus().data(), static_cast<int>(this->cpus().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.cpus"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string memory = 3;
       case 3: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_memory()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->memory().data(), static_cast<int>(this->memory().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.memory"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string pids = 4;
       case 4: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_pids()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->pids().data(), static_cast<int>(this->pids().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.pids"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string restart_policy = 5;
       case 5: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_restart_policy()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->restart_policy().data(), static_cast<int>(this->restart_policy().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.restart_policy"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       // string image_name = 6;
       case 6: {
         if (static_cast< ::google::protobuf::uint8>(tag) ==
             static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
           DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                 input, this->mutable_image_name()));
           DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
             this->image_name().data(), static_cast<int>(this->image_name().length()),
             ::google::protobuf::internal::WireFormatLite::PARSE,
             "containermanager.ContainerParameters.image_name"));
         } else {
           goto handle_unusual;
         }
         break;
       }
       default: {
       handle_unusual:
         if (tag == 0) {
           goto success;
         }
         DO_(::google::protobuf::internal::WireFormat::SkipField(
               input, tag, _internal_metadata_.mutable_unknown_fields()));
         break;
       }
     }
   }
 success:
   // @@protoc_insertion_point(parse_success:containermanager.ContainerParameters)
   return true;
 failure:
   // @@protoc_insertion_point(parse_failure:containermanager.ContainerParameters)
   return false;
 #undef DO_
 }
References container_name(), cpus(), DO_, image_name(), memory(), mutable_container_name(), mutable_cpus(), mutable_image_name(), mutable_memory(), mutable_pids(), mutable_restart_policy(), pids(), and restart_policy().
mutable_container_name()
std::string * containermanager::ContainerParameters::mutable_container_name () inline
Definition at line 433 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.container_name)
   return container_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_cpus()
std::string * containermanager::ContainerParameters::mutable_cpus () inline
Definition at line 486 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.cpus)
   return cpus_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_image_name()
std::string * containermanager::ContainerParameters::mutable_image_name () inline
Definition at line 698 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.image_name)
   return image_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_memory()
std::string * containermanager::ContainerParameters::mutable_memory () inline
Definition at line 539 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.memory)
   return memory_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_pids()
std::string * containermanager::ContainerParameters::mutable_pids () inline
Definition at line 592 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.pids)
   return pids_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
mutable_restart_policy()
std::string * containermanager::ContainerParameters::mutable_restart_policy () inline
Definition at line 645 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_mutable:containermanager.ContainerParameters.restart_policy)
   return restart_policy_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
Referenced by MergePartialFromCodedStream().
New() [1/2]
ContainerParameters* containermanager::ContainerParameters::New () const inline final
Definition at line 110 of file container_manager.pb.h.
{
     return CreateMaybeMessage<ContainerParameters>(NULL);
   }
New() [2/2]
ContainerParameters* containermanager::ContainerParameters::New (::google::protobuf::Arena * arena) const inline final
Definition at line 114 of file container_manager.pb.h.
{
     return CreateMaybeMessage<ContainerParameters>(arena);
   }
operator=()
ContainerParameters& containermanager::ContainerParameters::operator= (const ContainerParameters & from) inline
Definition at line 73 of file container_manager.pb.h.
{
     CopyFrom(from);
     return *this;
   }
References CopyFrom().
pids()
const ::std::string & containermanager::ContainerParameters::pids () const inline
Definition at line 563 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.pids)
   return pids_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_pids().
release_container_name()
std::string * containermanager::ContainerParameters::release_container_name () inline
Definition at line 438 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.container_name)
   return container_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_cpus()
std::string * containermanager::ContainerParameters::release_cpus () inline
Definition at line 491 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.cpus)
   return cpus_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_image_name()
std::string * containermanager::ContainerParameters::release_image_name () inline
Definition at line 703 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.image_name)
   return image_name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_memory()
std::string * containermanager::ContainerParameters::release_memory () inline
Definition at line 544 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.memory)
   return memory_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_pids()
std::string * containermanager::ContainerParameters::release_pids () inline
Definition at line 597 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.pids)
   return pids_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
release_restart_policy()
std::string * containermanager::ContainerParameters::release_restart_policy () inline
Definition at line 650 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_release:containermanager.ContainerParameters.restart_policy)
   return restart_policy_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
 }
restart_policy()
const ::std::string & containermanager::ContainerParameters::restart_policy () const inline
Definition at line 616 of file container_manager.pb.h.
{
   // @@protoc_insertion_point(field_get:containermanager.ContainerParameters.restart_policy)
   return restart_policy_.GetNoArena();
 }
Referenced by ByteSizeLong(), ContainerParameters(), InternalSerializeWithCachedSizesToArray(), MergeFrom(), MergePartialFromCodedStream(), SerializeWithCachedSizes(), and set_allocated_restart_policy().
SerializeWithCachedSizes()
void containermanager::ContainerParameters::SerializeWithCachedSizes (::google::protobuf::io::CodedOutputStream * output) const final
Definition at line 383 of file container_manager.pb.cc.
{
   // @@protoc_insertion_point(serialize_start:containermanager.ContainerParameters)
   ::google::protobuf::uint32 cached_has_bits = 0;
   (void) cached_has_bits;
   // string container_name = 1;
   if (this->container_name().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->container_name().data(), static_cast<int>(this->container_name().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.container_name");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       1, this->container_name(), output);
   }
   // string cpus = 2;
   if (this->cpus().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->cpus().data(), static_cast<int>(this->cpus().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.cpus");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       2, this->cpus(), output);
   }
   // string memory = 3;
   if (this->memory().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->memory().data(), static_cast<int>(this->memory().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.memory");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       3, this->memory(), output);
   }
   // string pids = 4;
   if (this->pids().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->pids().data(), static_cast<int>(this->pids().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.pids");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       4, this->pids(), output);
   }
   // string restart_policy = 5;
   if (this->restart_policy().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->restart_policy().data(), static_cast<int>(this->restart_policy().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.restart_policy");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       5, this->restart_policy(), output);
   }
   // string image_name = 6;
   if (this->image_name().size() > 0) {
     ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
       this->image_name().data(), static_cast<int>(this->image_name().length()),
       ::google::protobuf::internal::WireFormatLite::SERIALIZE,
       "containermanager.ContainerParameters.image_name");
     ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
       6, this->image_name(), output);
   }
   if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
     ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
         (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
   }
   // @@protoc_insertion_point(serialize_end:containermanager.ContainerParameters)
 }
References container_name(), cpus(), image_name(), memory(), pids(), and restart_policy().
set_allocated_container_name()
void containermanager::ContainerParameters::set_allocated_container_name (::std::string * container_name) inline
Definition at line 443 of file container_manager.pb.h.
{
   if (container_name != NULL) {
   } else {
   }
   container_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), container_name);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.container_name)
 }
References container_name().
set_allocated_cpus()
void containermanager::ContainerParameters::set_allocated_cpus (::std::string * cpus) inline
Definition at line 496 of file container_manager.pb.h.
{
   if (cpus != NULL) {
   } else {
   }
   cpus_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cpus);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.cpus)
 }
References cpus().
set_allocated_image_name()
void containermanager::ContainerParameters::set_allocated_image_name (::std::string * image_name) inline
Definition at line 708 of file container_manager.pb.h.
{
   if (image_name != NULL) {
   } else {
   }
   image_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_name);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.image_name)
 }
References image_name().
set_allocated_memory()
void containermanager::ContainerParameters::set_allocated_memory (::std::string * memory) inline
Definition at line 549 of file container_manager.pb.h.
{
   if (memory != NULL) {
   } else {
   }
   memory_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), memory);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.memory)
 }
References memory().
set_allocated_pids()
void containermanager::ContainerParameters::set_allocated_pids (::std::string * pids) inline
Definition at line 602 of file container_manager.pb.h.
{
   if (pids != NULL) {
   } else {
   }
   pids_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pids);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.pids)
 }
References pids().
set_allocated_restart_policy()
void containermanager::ContainerParameters::set_allocated_restart_policy (::std::string * restart_policy) inline
Definition at line 655 of file container_manager.pb.h.
{
   if (restart_policy != NULL) {
   } else {
   }
   restart_policy_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), restart_policy);
   // @@protoc_insertion_point(field_set_allocated:containermanager.ContainerParameters.restart_policy)
 }
References restart_policy().
set_container_name() [1/3]
void containermanager::ContainerParameters::set_container_name (const ::std::string & value) inline
Definition at line 408 of file container_manager.pb.h.
{
   container_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.container_name)
 }
set_container_name() [2/3]
void containermanager::ContainerParameters::set_container_name (const char * value) inline
Definition at line 421 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   container_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.container_name)
 }
set_container_name() [3/3]
void containermanager::ContainerParameters::set_container_name (const char * value, size_t size) inline
Definition at line 427 of file container_manager.pb.h.
{
   container_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.container_name)
 }
set_cpus() [1/3]
void containermanager::ContainerParameters::set_cpus (const ::std::string & value) inline
Definition at line 461 of file container_manager.pb.h.
{
   cpus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.cpus)
 }
set_cpus() [2/3]
void containermanager::ContainerParameters::set_cpus (const char * value) inline
Definition at line 474 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   cpus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.cpus)
 }
set_cpus() [3/3]
void containermanager::ContainerParameters::set_cpus (const char * value, size_t size) inline
Definition at line 480 of file container_manager.pb.h.
{
   cpus_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.cpus)
 }
set_image_name() [1/3]
void containermanager::ContainerParameters::set_image_name (const ::std::string & value) inline
Definition at line 673 of file container_manager.pb.h.
{
   image_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.image_name)
 }
set_image_name() [2/3]
void containermanager::ContainerParameters::set_image_name (const char * value) inline
Definition at line 686 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   image_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.image_name)
 }
set_image_name() [3/3]
void containermanager::ContainerParameters::set_image_name (const char * value, size_t size) inline
Definition at line 692 of file container_manager.pb.h.
{
   image_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.image_name)
 }
set_memory() [1/3]
void containermanager::ContainerParameters::set_memory (const ::std::string & value) inline
Definition at line 514 of file container_manager.pb.h.
{
   memory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.memory)
 }
set_memory() [2/3]
void containermanager::ContainerParameters::set_memory (const char * value) inline
Definition at line 527 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   memory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.memory)
 }
set_memory() [3/3]
void containermanager::ContainerParameters::set_memory (const char * value, size_t size) inline
Definition at line 533 of file container_manager.pb.h.
{
   memory_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.memory)
 }
set_pids() [1/3]
void containermanager::ContainerParameters::set_pids (const ::std::string & value) inline
Definition at line 567 of file container_manager.pb.h.
{
   pids_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.pids)
 }
set_pids() [2/3]
void containermanager::ContainerParameters::set_pids (const char * value) inline
Definition at line 580 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   pids_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.pids)
 }
set_pids() [3/3]
void containermanager::ContainerParameters::set_pids (const char * value, size_t size) inline
Definition at line 586 of file container_manager.pb.h.
{
   pids_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.pids)
 }
set_restart_policy() [1/3]
void containermanager::ContainerParameters::set_restart_policy (const ::std::string & value) inline
Definition at line 620 of file container_manager.pb.h.
{
   restart_policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
   // @@protoc_insertion_point(field_set:containermanager.ContainerParameters.restart_policy)
 }
set_restart_policy() [2/3]
void containermanager::ContainerParameters::set_restart_policy (const char * value) inline
Definition at line 633 of file container_manager.pb.h.
{
   GOOGLE_DCHECK(value != NULL);
   restart_policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
   // @@protoc_insertion_point(field_set_char:containermanager.ContainerParameters.restart_policy)
 }
set_restart_policy() [3/3]
void containermanager::ContainerParameters::set_restart_policy (const char * value, size_t size) inline
Definition at line 639 of file container_manager.pb.h.
{
   restart_policy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
       ::std::string(reinterpret_cast<const char*>(value), size));
   // @@protoc_insertion_point(field_set_pointer:containermanager.ContainerParameters.restart_policy)
 }
Swap()
void containermanager::ContainerParameters::Swap (ContainerParameters * other)
Definition at line 659 of file container_manager.pb.cc.
{
   if (other == this) return;
   InternalSwap(other);
 }
Friends And Related Function Documentation
::protobuf_container_5fmanager_2eproto::TableStruct
friend struct ::protobuf_container_5fmanager_2eproto::TableStruct friend
Definition at line 248 of file container_manager.pb.h.
swap
void swap (ContainerParameters & a, ContainerParameters & b) friend
Definition at line 104 of file container_manager.pb.h.
{
     a.Swap(&b);
   }
Member Data Documentation
kContainerNameFieldNumber
const int containermanager::ContainerParameters::kContainerNameFieldNumber = 1 static
Definition at line 155 of file container_manager.pb.h.
kCpusFieldNumber
const int containermanager::ContainerParameters::kCpusFieldNumber = 2 static
Definition at line 169 of file container_manager.pb.h.
kImageNameFieldNumber
const int containermanager::ContainerParameters::kImageNameFieldNumber = 6 static
Definition at line 225 of file container_manager.pb.h.
kIndexInFileMessages
constexpr int containermanager::ContainerParameters::kIndexInFileMessages static constexpr
Initial value:
=
    0
Definition at line 100 of file container_manager.pb.h.
Referenced by descriptor(), and GetMetadata().
kMemoryFieldNumber
const int containermanager::ContainerParameters::kMemoryFieldNumber = 3 static
Definition at line 183 of file container_manager.pb.h.
kPidsFieldNumber
const int containermanager::ContainerParameters::kPidsFieldNumber = 4 static
Definition at line 197 of file container_manager.pb.h.
kRestartPolicyFieldNumber
const int containermanager::ContainerParameters::kRestartPolicyFieldNumber = 5 static
Definition at line 211 of file container_manager.pb.h.
The documentation for this class was generated from the following files:
executor/proto/generated/container_manager.pb.h
executor/proto/generated/container_manager.pb.cc