Container Manager: PodmanRestartContainerCommand Class Reference
PodmanRestartContainerCommand Class Reference
Command to restart a Podman container.
#include <podman_commands.hpp>
Public Member Functions
PodmanRestartContainerCommand (const ContainerRequest &req)
Constructs a PodmanRestartContainerCommand.
~PodmanRestartContainerCommand ()=default
Destructor.
Status Execute () const override
Executes the command to restart a Podman container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to restart a Podman container.
Parameters
req The container request containing the container name.
Definition at line 149 of file podman_commands.hpp.
Constructor & Destructor Documentation
PodmanRestartContainerCommand()
PodmanRestartContainerCommand::PodmanRestartContainerCommand (const ContainerRequest & req) explicit
Constructs a PodmanRestartContainerCommand.
Parameters
req The container request containing the container name.
Definition at line 150 of file podman_commands.cpp.
 : req_(req) {}
~PodmanRestartContainerCommand()
PodmanRestartContainerCommand::~PodmanRestartContainerCommand () default
Destructor.
Member Function Documentation
Execute()
Status PodmanRestartContainerCommand::Execute () const override virtual
Executes the command to restart a Podman container.
Returns
Status indicating if the container was restarted successfully.
Executes the command to restart a Podman container.
Returns
Status indicating if the container was restarted successfully.
Implements Command.
Definition at line 154 of file podman_commands.cpp.
{
     std::string command = FormatCommand(
         CommandTemplate::Restart,
         {{"runtime", "podman"}, {"name", req_.container_name}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Podman container restarted successfully" << std::endl;
         return Status::Ok();
     } else {
         std::string msg = "Failed to restart Podman container, exit code: " + std::to_string(status);
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::InternalError, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, ContainerRequest::container_name, Status::Error(), FormatCommand(), InternalError, Status::Ok(), and CommandTemplate::Restart.
The documentation for this class was generated from the following files:
runtime/inc/podman_commands.hpp
runtime/src/podman_commands.cpp