Container Manager: JsonRequestExecutorHandler Class Reference
JsonRequestExecutorHandler Class Reference
Parses and executes JSON requests with optional encryption support.
#include <json_request_executor.hpp>
Public Member Functions
JsonRequestExecutorHandler (IDatabaseHandler &db, ContainerServiceHandler &service, ISecurityProvider &security_provider)
Constructs a JsonRequestExecutorHandler with injected dependencies.
nlohmann::json Execute (const std::string &data) override
Executes a request represented as a JSON string. Handles decryption if the payload is encrypted.
Public Member Functions inherited from RequestExecutor
virtual ~RequestExecutor ()=default
Virtual destructor for safe polymorphic destruction.
Detailed Description
Parses and executes JSON requests with optional encryption support.
This class is responsible for:
Receiving JSON (or encrypted JSON) payloads from protocol handlers.
Detecting and decrypting encrypted payloads if necessary.
Parsing and validating the JSON request.
Transforming and saving the request to the database.
Invoking the container service handler to perform the requested operation.
Returning the result as a JSON object.
Used by all protocol consumers (REST, MQTT, MQ, D-Bus) for JSON data format.
Definition at line 39 of file json_request_executor.hpp.
Constructor & Destructor Documentation
JsonRequestExecutorHandler()
JsonRequestExecutorHandler::JsonRequestExecutorHandler (IDatabaseHandler & db, ContainerServiceHandler & service, ISecurityProvider & security_provider)
Constructs a JsonRequestExecutorHandler with injected dependencies.
Constructor for JsonRequestExecutorHandler.
Parameters
db Reference to an IDatabaseHandler implementation.
service Reference to a ContainerServiceHandler.
security_provider Reference to a security provider for decryption.
db Reference to the database handler.
service Reference to the container service handler.
security_provider Reference to the security provider for decryption.
Definition at line 28 of file json_request_executor.cpp.
     : db_(db), service_(service), security_provider_(security_provider) {}
Member Function Documentation
Execute()
nlohmann::json JsonRequestExecutorHandler::Execute (const std::string & data) override virtual
Executes a request represented as a JSON string. Handles decryption if the payload is encrypted.
Executes a request represented as a JSON string. Handles decryption if the payload is encrypted, parses and validates the JSON, transforms and saves the request to the database, and invokes the container service handler.
Parameters
data The input data as a JSON string (or encrypted data).
Returns
A JSON object containing the result of the execution.
Implements RequestExecutor.
Definition at line 68 of file json_request_executor.cpp.
{
     try {
         std::string json_str;
 #if defined(ENABLE_ENCRYPTION) && ENABLE_ENCRYPTION
         // Improved encryption detection
         if (IsEncryptedData(data)) {
             // Data appears to be encrypted - attempt decryption
             if (!security_provider_.Decrypt(data, json_str)) {
                 std::cerr << "[Executor] Decryption failed for encrypted data" << std::endl;
                 Status error_status = Status::Error(StatusCode::InvalidArgument, "Decryption failed");
                 return {
                     {"status", "error"},
                     {"code", static_cast<int>(error_status.code)},
                     {"message", error_status.message}
                 };
             }
             std::cout << "[Executor] Successfully decrypted data" << std::endl;
         } else {
             // Data appears to be plain JSON
             json_str = data;
             std::cout << "[Executor] Processing unencrypted JSON data" << std::endl;
         }
 #else
         // Encryption disabled - treat all data as plain JSON
         json_str = data;
         std::cout << "[Executor] Processing data (encryption disabled)" << std::endl;
 #endif
         // Parse JSON
         json j = json::parse(json_str);
         // Transform and save to database
         json transformed;
         transformed["runtime"] = j.value("runtime", "");
         transformed["status"] = kEmptyString;
         transformed["parameters"] = j.value("parameters", json::array());
         if (!transformed["parameters"].empty() && transformed["parameters"][0].is_object()) {
             transformed["parameters"][0].erase("container_name");
         }
         std::string key = j["parameters"][0].value("container_name", "unknown_container");
         db_.SaveJson(key, transformed);
         // Create container request
         ContainerRequest req;
         req.operation = j.value("operation", "");
         req.runtime = j.value("runtime", "");
         if (!j["parameters"].empty()) {
             const auto& param = j["parameters"][0];
             req.container_name = param.value("container_name", "");
             req.image_name = param.value("image_name", "");
             req.cpus = param.value("cpus", "");
             req.memory = param.value("memory", "");
             req.pids = param.value("pids", "");
             req.restart_policy = param.value("restart_policy", "");
         }
         return service_.HandleRequest(req);
     } catch (const json::parse_error& e) {
         std::cerr << "[Executor] JSON parsing failed: " << e.what() << std::endl;
         Status error_status = Status::Error(StatusCode::InvalidArgument, "JSON parsing failed");
         return {
             {"status", "error"},
             {"code", static_cast<int>(error_status.code)},
             {"message", error_status.message}
         };
     } catch (const std::exception& e) {
         std::cerr << "[Executor] Execution failed: " << e.what() << std::endl;
         Status error_status = Status::Error(StatusCode::InvalidArgument, e.what());
         return {
             {"status", "error"},
             {"code", static_cast<int>(error_status.code)},
             {"message", error_status.message}
         };
     }
 }
References Status::code, ContainerRequest::container_name, ContainerRequest::cpus, ISecurityProvider::Decrypt(), Status::Error(), ContainerServiceHandler::HandleRequest(), ContainerRequest::image_name, InvalidArgument, kEmptyString, ContainerRequest::memory, Status::message, ContainerRequest::operation, ContainerRequest::pids, ContainerRequest::restart_policy, ContainerRequest::runtime, and IDatabaseHandler::SaveJson().
The documentation for this class was generated from the following files:
executor/inc/json_request_executor.hpp
executor/src/json_request_executor.cpp