Container Manager: DbusConsumer Class Reference
DbusConsumer Class Reference
Handles receiving and processing JSON requests over D-Bus.
#include <dbus_consumer.hpp>
Public Member Functions
DbusConsumer (const DbusConfig &config, std::shared_ptr< RequestExecutor > executor)
Construct a DbusConsumer.
~DbusConsumer ()
Destructor. Stops the consumer if running.
void Start ()
Start listening for D-Bus method calls in a background thread.
void Stop ()
Stop listening and join the background thread.
Detailed Description
Handles receiving and processing JSON requests over D-Bus.
This class connects to the D-Bus session bus, registers an object and interface, and listens for incoming method calls (e.g., "Execute") from other applications. Incoming JSON payloads are forwarded to the shared RequestExecutor for processing.
Definition at line 24 of file dbus_consumer.hpp.
Constructor & Destructor Documentation
DbusConsumer()
DbusConsumer::DbusConsumer (const DbusConfig & config, std::shared_ptr< RequestExecutor > executor)
Construct a DbusConsumer.
Parameters
config The DbusConfig struct containing bus name, object path, and interface.
executor Shared pointer to the request executor for processing incoming requests.
Definition at line 9 of file dbus_consumer.cpp.
     : config_(config), executor_(std::move(executor)), running_(false) {}
~DbusConsumer()
DbusConsumer::~DbusConsumer ()
Destructor. Stops the consumer if running.
Definition at line 12 of file dbus_consumer.cpp.
{
     Stop();
 }
References Stop().
Member Function Documentation
Start()
void DbusConsumer::Start ()
Start listening for D-Bus method calls in a background thread.
Definition at line 16 of file dbus_consumer.cpp.
{
     running_ = true;
     listenThread_ = std::thread(&DbusConsumer::ListenLoop, this);
 }
Referenced by main().
Stop()
void DbusConsumer::Stop ()
Stop listening and join the background thread.
Definition at line 21 of file dbus_consumer.cpp.
{
     running_ = false;
     if (listenThread_.joinable())
         listenThread_.join();
 }
Referenced by main(), and ~DbusConsumer().
The documentation for this class was generated from the following files:
api/inc/dbus_consumer.hpp
api/src/dbus_consumer.cpp