Container Manager: DockerApiRuntimeAvailableCommand Class Reference
DockerApiRuntimeAvailableCommand Class Reference
Command to check if Docker daemon is available via the API.
#include <docker_api_commands.hpp>
Public Member Functions
DockerApiRuntimeAvailableCommand ()
Constructs a DockerApiRuntimeAvailableCommand.
~DockerApiRuntimeAvailableCommand ()=default
Destructor.
Status Execute () const override
Executes the command to check Docker API runtime availability.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to check if Docker daemon is available via the API.
Definition at line 22 of file docker_api_commands.hpp.
Constructor & Destructor Documentation
DockerApiRuntimeAvailableCommand()
DockerApiRuntimeAvailableCommand::DockerApiRuntimeAvailableCommand () explicit
Constructs a DockerApiRuntimeAvailableCommand.
Definition at line 23 of file docker_api_commands.cpp.
 {}
~DockerApiRuntimeAvailableCommand()
DockerApiRuntimeAvailableCommand::~DockerApiRuntimeAvailableCommand () default
Destructor.
Member Function Documentation
Execute()
Status DockerApiRuntimeAvailableCommand::Execute () const override virtual
Executes the command to check Docker API runtime availability.
Returns
Status indicating if Docker is running.
Executes the command to check Docker API runtime availability.
Returns
Status indicating if Docker is running.
Implements Command.
Definition at line 27 of file docker_api_commands.cpp.
{
     CurlHandler curl;
     std::string response;
     std::string url = std::string(kDockerApiBaseUrl) + std::string(ApiEndpoint::Ping);
     bool success = curl.GetUnix(url, kDockerUnixSocketPath, response);
     if (success && response == "OK") {
         CM_LOG_INFO << "[Docker API] Docker daemon is running (/_ping returned OK)." << std::endl;
         return Status::Ok();
     } else if (success) {
         std::string msg = "[Docker API] Docker daemon responded, but not OK: " + response;
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::Unavailable, msg);
     } else {
         std::string msg = "[Docker API] Failed to contact Docker daemon.";
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::Unavailable, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, Status::Error(), CurlHandler::GetUnix(), kDockerApiBaseUrl, kDockerUnixSocketPath, Status::Ok(), ApiEndpoint::Ping, and Unavailable.
The documentation for this class was generated from the following files:
runtime/inc/docker_api_commands.hpp
runtime/src/docker_api_commands.cpp