Container Manager: DockerApiRestartContainerCommand Class Reference
DockerApiRestartContainerCommand Class Reference
Command to restart a Docker container via the Docker API.
#include <docker_api_commands.hpp>
Public Member Functions
DockerApiRestartContainerCommand (const ContainerRequest &req)
Constructs a DockerApiRestartContainerCommand.
~DockerApiRestartContainerCommand ()=default
Destructor.
Status Execute () const override
Executes the command to restart a Docker container via the API.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to restart a Docker container via the Docker API.
Parameters
req The container request containing the container name.
Definition at line 123 of file docker_api_commands.hpp.
Constructor & Destructor Documentation
DockerApiRestartContainerCommand()
DockerApiRestartContainerCommand::DockerApiRestartContainerCommand (const ContainerRequest & req) explicit
Constructs a DockerApiRestartContainerCommand.
Parameters
req The container request containing the container name.
Definition at line 169 of file docker_api_commands.cpp.
 : req_(req) {}
~DockerApiRestartContainerCommand()
DockerApiRestartContainerCommand::~DockerApiRestartContainerCommand () default
Destructor.
Member Function Documentation
Execute()
Status DockerApiRestartContainerCommand::Execute () const override virtual
Executes the command to restart a Docker container via the API.
Returns
Status indicating if the container was restarted successfully.
Executes the command to restart a Docker container via the API.
Returns
Status indicating if the container was restarted successfully.
Implements Command.
Definition at line 173 of file docker_api_commands.cpp.
{
     CurlHandler curl;
     std::string response;
     std::string url = ComposeContainerApiEndpoint(
         kDockerApiBaseUrl, req_.container_name, ApiEndpoint::Restart
     );
     bool success = curl.PostUnix(url, kDockerUnixSocketPath, "", response, "application/json");
     if (success) {
         CM_LOG_INFO << "[Docker API] Restart container response: " << response;
         return Status::Ok();
     } else {
         std::string msg = "[Docker API] Failed to restart container. Response: " + response;
         CM_LOG_ERROR << msg;
         return Status::Error(StatusCode::InternalError, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, ComposeContainerApiEndpoint(), ContainerRequest::container_name, Status::Error(), InternalError, kDockerApiBaseUrl, kDockerUnixSocketPath, Status::Ok(), CurlHandler::PostUnix(), and ApiEndpoint::Restart.
The documentation for this class was generated from the following files:
runtime/inc/docker_api_commands.hpp
runtime/src/docker_api_commands.cpp