Container Manager: DockerRestartContainerCommand Class Reference
DockerRestartContainerCommand Class Reference
Command to restart a Docker container.
#include <docker_commands.hpp>
Public Member Functions
DockerRestartContainerCommand (const std::string &container_name_)
Constructs a DockerRestartContainerCommand.
~DockerRestartContainerCommand ()=default
Destructor.
bool Execute () const override
Executes the command to restart a Docker container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Destructor.
Detailed Description
Command to restart a Docker container.
Definition at line 133 of file docker_commands.hpp.
Constructor & Destructor Documentation
DockerRestartContainerCommand()
DockerRestartContainerCommand::DockerRestartContainerCommand (const std::string & container_name_) explicit
Constructs a DockerRestartContainerCommand.
Parameters
container_name_ Name of the container to restart.
Definition at line 120 of file docker_commands.cpp.
                                                                                             : container_name_(container_name) {
     // Empty constructor
 }
~DockerRestartContainerCommand()
DockerRestartContainerCommand::~DockerRestartContainerCommand () default
Destructor.
Member Function Documentation
Execute()
bool DockerRestartContainerCommand::Execute () const override virtual
Executes the command to restart a Docker container.
Returns
True if the container was restarted successfully, false otherwise.
Implements Command.
Definition at line 124 of file docker_commands.cpp.
{
     // Stop the Docker container
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     std::string command = FormatCommand(
         CommandTemplate::Restart,
         {{"runtime", "docker"}, {"name", container_name_}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Docker container restarted successfully";
         db.UpdateField(container_name_, "status", "running");
         return true;
     } else {
         CM_LOG_ERROR << "Failed to restart Docker container";
         db.UpdateField(container_name_, "status", "Error restarting container");
         return false;
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, FormatCommand(), RedisDatabaseHandler::GetInstance(), CommandTemplate::Restart, and IDatabaseHandler::UpdateField().
The documentation for this class was generated from the following files:
runtime/inc/docker_commands.hpp
runtime/src/docker_commands.cpp