Container Manager: ProtoRequestExecutorHandler Class Reference
ProtoRequestExecutorHandler Class Reference
#include <protobuf_request_executor.hpp>
Public Member Functions
ProtoRequestExecutorHandler ()
~ProtoRequestExecutorHandler () override=default
nlohmann::json Execute (const std::string &proto_data) override
Executes a request and returns a JSON response.
Public Member Functions inherited from RequestExecutor
virtual ~RequestExecutor ()=default
Virtual destructor for safe polymorphic destruction.
Detailed Description
Definition at line 16 of file protobuf_request_executor.hpp.
Constructor & Destructor Documentation
ProtoRequestExecutorHandler()
ProtoRequestExecutorHandler::ProtoRequestExecutorHandler () default
~ProtoRequestExecutorHandler()
ProtoRequestExecutorHandler::~ProtoRequestExecutorHandler () override default
Member Function Documentation
Execute()
nlohmann::json ProtoRequestExecutorHandler::Execute (const std::string & data) override virtual
Executes a request and returns a JSON response.
Parameters
data The input data as a string (could be JSON, Protobuf, etc.).
Returns
A JSON object containing the result of the execution.
Implements RequestExecutor.
Definition at line 22 of file protobuf_request_executor.cpp.
{
     containermanager::ContainerRequest proto_req;
     if (!proto_req.ParseFromString(proto_data)) {
         // Return error as JSON
         return {{"status", "error"}, {"message", "Failed to parse protobuf"}};
     }
     // Convert proto to JSON for DB storage
     nlohmann::json transformed;
     transformed["runtime"] = proto_req.runtime();
     transformed["status"] = kEmptyString;
     transformed["parameters"] = nlohmann::json::array();
     for (const auto& param : proto_req.parameters()) {
         nlohmann::json param_json;
         param_json["container_name"] = param.container_name();
         param_json["cpus"] = param.cpus();
         param_json["memory"] = param.memory();
         param_json["pids"] = param.pids();
         param_json["restart_policy"] = param.restart_policy();
         param_json["image_name"] = param.image_name();
         transformed["parameters"].push_back(param_json);
     }
     // Save to DB (use first parameter's container_name as key if available)
     std::string key = "unknown_container";
     if (!proto_req.parameters().empty()) {
         key = proto_req.parameters(0).container_name();
         // Remove "container_name" from parameters[0] for DB storage, as in JSON executor
         transformed["parameters"][0].erase("container_name");
     }
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     db.SaveJson(key, transformed);
     // Fill internal ContainerRequest struct
     ContainerRequest req;
     req.runtime = proto_req.runtime();
     req.operation = proto_req.operation();
     if (!proto_req.parameters().empty()) {
         const auto& param = proto_req.parameters(0);
         req.container_name = param.container_name();
     }
     // Call business logic and return result
     return ContainerServiceHandler::HandleRequest(req);
 }
References ContainerRequest::container_name, containermanager::ContainerParameters::container_name(), RedisDatabaseHandler::GetInstance(), ContainerServiceHandler::HandleRequest(), kEmptyString, ContainerRequest::operation, containermanager::ContainerRequest::operation(), containermanager::ContainerRequest::parameters(), ContainerRequest::runtime, containermanager::ContainerRequest::runtime(), and IDatabaseHandler::SaveJson().
The documentation for this class was generated from the following files:
executor/inc/protobuf_request_executor.hpp
executor/src/protobuf_request_executor.cpp