Container Manager: DockerApiStopContainerCommand Class Reference
DockerApiStopContainerCommand Class Reference
Command to stop a Docker container via the Docker API.
#include <docker_api_commands.hpp>
Public Member Functions
DockerApiStopContainerCommand (const ContainerRequest &req)
Constructs a DockerApiStopContainerCommand.
~DockerApiStopContainerCommand ()=default
Destructor.
Status Execute () const override
Executes the command to stop a Docker container via the API.
Public Member Functions inherited from Command
virtual ~Command ()=default
Virtual destructor.
Detailed Description
Command to stop a Docker container via the Docker API.
Parameters
req The container request containing the container name.
Definition at line 97 of file docker_api_commands.hpp.
Constructor & Destructor Documentation
DockerApiStopContainerCommand()
DockerApiStopContainerCommand::DockerApiStopContainerCommand (const ContainerRequest & req) explicit
Constructs a DockerApiStopContainerCommand.
Parameters
req The container request containing the container name.
Definition at line 143 of file docker_api_commands.cpp.
 : req_(req) {}
~DockerApiStopContainerCommand()
DockerApiStopContainerCommand::~DockerApiStopContainerCommand () default
Destructor.
Member Function Documentation
Execute()
Status DockerApiStopContainerCommand::Execute () const override virtual
Executes the command to stop a Docker container via the API.
Returns
Status indicating if the container was stopped successfully.
Executes the command to stop a Docker container via the API.
Returns
Status indicating if the container was stopped successfully.
Implements Command.
Definition at line 147 of file docker_api_commands.cpp.
{
     CurlHandler curl;
     std::string response;
     std::string url = ComposeContainerApiEndpoint(
         kDockerApiBaseUrl, req_.container_name, ApiEndpoint::Stop
     );
     bool success = curl.PostUnix(url, kDockerUnixSocketPath, "", response, "application/json");
     if (success) {
         CM_LOG_INFO << "[Docker API] Stop container response: " << response << std::endl;
         return Status::Ok();
     } else {
         std::string msg = "[Docker API] Failed to stop container. Response: " + response;
         CM_LOG_ERROR << msg << std::endl;
         return Status::Error(StatusCode::InternalError, msg);
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, ComposeContainerApiEndpoint(), ContainerRequest::container_name, Status::Error(), InternalError, kDockerApiBaseUrl, kDockerUnixSocketPath, Status::Ok(), CurlHandler::PostUnix(), and ApiEndpoint::Stop.
The documentation for this class was generated from the following files:
runtime/inc/docker_api_commands.hpp
runtime/src/docker_api_commands.cpp