Container Manager: PodmanStopContainerCommand Class Reference
PodmanStopContainerCommand Class Reference
Command to stop a Podman container.
#include <podman_commands.hpp>
Public Member Functions
PodmanStopContainerCommand (const std::string &container_name_)
Constructs a PodmanStopContainerCommand.
~PodmanStopContainerCommand ()=default
Destructor.
bool Execute () const override
Executes the command to stop a Podman container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Destructor.
Detailed Description
Command to stop a Podman container.
Definition at line 88 of file podman_commands.hpp.
Constructor & Destructor Documentation
PodmanStopContainerCommand()
PodmanStopContainerCommand::PodmanStopContainerCommand (const std::string & container_name_) explicit
Constructs a PodmanStopContainerCommand.
Parameters
container_name_ Name of the container to stop.
Definition at line 73 of file podman_commands.cpp.
                                                                                       : container_name_(container_name) {
     // Empty constructor
 }
~PodmanStopContainerCommand()
PodmanStopContainerCommand::~PodmanStopContainerCommand () default
Destructor.
Member Function Documentation
Execute()
bool PodmanStopContainerCommand::Execute () const override virtual
Executes the command to stop a Podman container.
Returns
True if the container was stopped successfully, false otherwise.
Implements Command.
Definition at line 77 of file podman_commands.cpp.
{
     // Stop the Podman container
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     std::string command = FormatCommand(
         CommandTemplate::Stop,
         {{"runtime", "podman"}, {"name", container_name_}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Podman container stopped successfully";
         db.UpdateField(container_name_, "status", "stopped");
         return true;
     } else {
         CM_LOG_ERROR << "Failed to stop Podman container";
         db.UpdateField(container_name_, "status", "Error stopping container");
         return false;
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, FormatCommand(), RedisDatabaseHandler::GetInstance(), CommandTemplate::Stop, and IDatabaseHandler::UpdateField().
The documentation for this class was generated from the following files:
runtime/inc/podman_commands.hpp
runtime/src/podman_commands.cpp