Container Manager: IDatabaseHandler Class Reference
IDatabaseHandler Class Reference abstract
Interface for database handlers supporting JSON storage and retrieval.
#include <database_interface.hpp>
Public Member Functions
virtual ~IDatabaseHandler ()=default
Virtual destructor for safe polymorphic destruction.
virtual void SaveJson (const std::string &key, const nlohmann::json &value)=0
Saves a JSON object to the database with the specified key.
virtual nlohmann::json GetJson (const std::string &key)=0
Retrieves a JSON object from the database by key.
virtual void ClearDatabase ()=0
Clears all data from the database.
virtual void UpdateField (const std::string &key, const std::string &field, const std::string &value)=0
Updates a specific field in the JSON object stored under the given key.
virtual void RemoveKey (const std::string &key)=0
Removes the JSON object associated with the specified key from the database.
Detailed Description
Interface for database handlers supporting JSON storage and retrieval.
This interface defines the contract for database operations such as saving, retrieving, updating, and removing JSON objects by key. Implementations can support different backend databases.
Definition at line 17 of file database_interface.hpp.
Constructor & Destructor Documentation
~IDatabaseHandler()
virtual IDatabaseHandler::~IDatabaseHandler () virtual default
Virtual destructor for safe polymorphic destruction.
Member Function Documentation
ClearDatabase()
virtual void IDatabaseHandler::ClearDatabase () pure virtual
Clears all data from the database.
Implemented in EmbeddedDatabaseHandler, and RedisDatabaseHandler.
Referenced by InitDatabase().
GetJson()
virtual nlohmann::json IDatabaseHandler::GetJson (const std::string & key) pure virtual
Retrieves a JSON object from the database by key.
Parameters
key The key of the JSON object to retrieve.
Returns
The JSON object associated with the key, or an empty object if not found.
Implemented in EmbeddedDatabaseHandler, and RedisDatabaseHandler.
RemoveKey()
virtual void IDatabaseHandler::RemoveKey (const std::string & key) pure virtual
Removes the JSON object associated with the specified key from the database.
Parameters
key The key of the JSON object to remove.
Implemented in EmbeddedDatabaseHandler, and RedisDatabaseHandler.
Referenced by ContainerServiceHandler::HandleRequest().
SaveJson()
virtual void IDatabaseHandler::SaveJson (const std::string & key, const nlohmann::json & value) pure virtual
Saves a JSON object to the database with the specified key.
Parameters
key The key under which the JSON object will be stored.
value The JSON object to store.
Implemented in EmbeddedDatabaseHandler, and RedisDatabaseHandler.
Referenced by JsonRequestExecutorHandler::Execute(), and ProtoRequestExecutorHandler::Execute().
UpdateField()
virtual void IDatabaseHandler::UpdateField (const std::string & key, const std::string & field, const std::string & value) pure virtual
Updates a specific field in the JSON object stored under the given key.
Parameters
key The key of the JSON object to update.
field The field within the JSON object to update.
value The new value for the specified field.
Implemented in EmbeddedDatabaseHandler, and RedisDatabaseHandler.
Referenced by ContainerServiceHandler::HandleRequest().
The documentation for this class was generated from the following file:
database/inc/database_interface.hpp