Container Manager: DockerCreateContainerCommand Class Reference
DockerCreateContainerCommand Class Reference
Command to create a Docker container with specified parameters.
#include <docker_commands.hpp>
Public Member Functions
DockerCreateContainerCommand (const std::string &container_name_)
Constructs a DockerCreateContainerCommand.
~DockerCreateContainerCommand ()=default
Destructor.
bool Execute () const override
Executes the command to create a Docker container.
Public Member Functions inherited from Command
virtual ~Command ()=default
Destructor.
Detailed Description
Command to create a Docker container with specified parameters.
Definition at line 35 of file docker_commands.hpp.
Constructor & Destructor Documentation
DockerCreateContainerCommand()
DockerCreateContainerCommand::DockerCreateContainerCommand (const std::string & container_name_) explicit
Constructs a DockerCreateContainerCommand.
Parameters
container_name_ Name of the container to create.
Definition at line 32 of file docker_commands.cpp.
                                                                                           : container_name_(container_name) {
     // Empty constructor
 }
~DockerCreateContainerCommand()
DockerCreateContainerCommand::~DockerCreateContainerCommand () default
Destructor.
Member Function Documentation
Execute()
bool DockerCreateContainerCommand::Execute () const override virtual
Executes the command to create a Docker container.
Returns
True if the container was created successfully, false otherwise.
Implements Command.
Definition at line 36 of file docker_commands.cpp.
{
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     nlohmann::json config = db.GetJson(container_name_);
     std::string image_name_;
     if (!config["parameters"].empty() && config["parameters"][0].contains("image_name")) {
         image_name_ = config["parameters"][0]["image_name"].get<std::string>();
     } else {
         image_name_ = "";
     }
     // Start the Docker container
     std::string command = FormatCommand(
         CommandTemplate::Create,
         {{"runtime", "docker"}, {"name", container_name_}, {"image", image_name_}}
     );
     int status = std::system(command.c_str());
     if (status == 0) {
         CM_LOG_INFO << "Docker container created successfully";
         db.UpdateField(container_name_, "status", "created");
         return true;
     } else {
         CM_LOG_ERROR << "Failed to create Docker container";
         db.UpdateField(container_name_, "status", "Error creating container");
         return false;
     }
 }
References CM_LOG_ERROR, CM_LOG_INFO, CommandTemplate::Create, FormatCommand(), RedisDatabaseHandler::GetInstance(), IDatabaseHandler::GetJson(), and IDatabaseHandler::UpdateField().
The documentation for this class was generated from the following files:
runtime/inc/docker_commands.hpp
runtime/src/docker_commands.cpp