Container Manager: utils/inc/common.hpp File Reference
common.hpp File Reference
Defines common constants, string views, and utility structures for the application.
#include <string>
#include <string_view>
#include <unordered_map>
Classes
struct ServerConfig
Holds constant configuration for the HTTP server.
struct MqttConfig
Holds constant configuration for the MQTT subscriber.
struct MessageQueueConfig
Holds constant configuration for the POSIX message queue consumer.
struct DbusConfig
Holds constant configuration for the D-Bus consumer (session bus).
struct RuntimeName
Contains string constants for supported container runtimes.
struct CommandName
Contains string constants for supported container operations.
Namespaces
CommandTemplate
Contains command templates for supported container operations. Placeholders (e.g., {runtime}, {name}, {image}) are replaced at runtime.
ApiEndpoint
Contains API endpoint templates for container operations.
Functions
std::string FormatCommand (std::string_view tmpl, const std::unordered_map< std::string, std::string > &values)
Utility function to format command templates by replacing placeholders with actual values.
std::string ComposeContainerApiEndpoint (std::string_view baseUrl, std::string_view containerName, std::string_view action)
Compose a container API endpoint for Docker or Podman API.
Variables
const std::string kEmptyString = ""
Represents an empty string constant.
const std::string kContainerManagerLogName = "cm_log"
Name used for container manager in google logging.
constexpr int kMainShutdownPollMs = 200
Sleep interval (in milliseconds) for main thread shutdown polling.
constexpr size_t kMaxEntries = 32
Maximum number of entries for embedded database.
constexpr size_t kMaxKeyLen = 32
Maximum key length for embedded database entries.
constexpr char kDockerUnixSocketPath [] = "/var/run/docker.sock"
Docker Unix socket path and API base URL for HTTP API communication.
constexpr char kDockerApiBaseUrl [] = "http://localhost/v1.49/"
constexpr char kPodmanUnixSocketPath [] = "/run/user/1000/podman/podman.sock"
Podman Unix socket path and API base URL for HTTP API communication.
constexpr char kPodmanApiBaseUrl [] = "http://d/v3.0.0/"
constexpr std::string_view CommandTemplate::Create
constexpr std::string_view CommandTemplate::Start = "{runtime} start {name}"
constexpr std::string_view CommandTemplate::Stop = "{runtime} stop {name}"
constexpr std::string_view CommandTemplate::Remove = "{runtime} rm -f {name}"
constexpr std::string_view CommandTemplate::Restart = "{runtime} restart {name}"
constexpr std::string_view ApiEndpoint::Containers = "containers/"
constexpr std::string_view ApiEndpoint::Create = "containers/create?name="
constexpr std::string_view ApiEndpoint::Start = "/start"
constexpr std::string_view ApiEndpoint::Stop = "/stop"
constexpr std::string_view ApiEndpoint::Restart = "/restart"
constexpr std::string_view ApiEndpoint::Remove = "?force=true"
constexpr std::string_view ApiEndpoint::Ping = "_ping"
Detailed Description
Defines common constants, string views, and utility structures for the application.
This header centralizes configuration constants, runtime and command names, command templates, and utility functions used throughout the container manager application. It is designed to promote consistency and reduce duplication across modules.
Definition in file common.hpp.
Function Documentation
ComposeContainerApiEndpoint()
std::string ComposeContainerApiEndpoint (std::string_view baseUrl, std::string_view containerName, std::string_view action) inline
Compose a container API endpoint for Docker or Podman API.
Parameters
baseUrl The API base URL (e.g., kDockerApiBaseUrl or kPodmanApiBaseUrl).
containerName The container name.
action The action endpoint (e.g., ApiEndpoint::Start, ApiEndpoint::Stop).
Returns
The full endpoint URL as a std::string.
Definition at line 144 of file common.hpp.
 {
     return std::string(baseUrl) + std::string(ApiEndpoint::Containers) +
            std::string(containerName) + std::string(action);
 }
References ApiEndpoint::Containers.
Referenced by DockerApiStartContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), PodmanApiStopContainerCommand::Execute(), DockerApiRestartContainerCommand::Execute(), and DockerApiRemoveContainerCommand::Execute().
FormatCommand()
std::string FormatCommand (std::string_view tmpl, const std::unordered_map< std::string, std::string > & values) inline
Utility function to format command templates by replacing placeholders with actual values.
Parameters
tmpl The command template string with placeholders.
values A map of placeholder names to their replacement values.
Returns
The formatted command string.
Definition at line 114 of file common.hpp.
{
     std::string result(tmpl);
     for (const auto& [key, val] : values) {
         std::string placeholder = "{" + key + "}";
         size_t pos = 0;
         while ((pos = result.find(placeholder, pos)) != std::string::npos) {
             result.replace(pos, placeholder.length(), val);
             pos += val.length();
         }
     }
     return result;
 }
Referenced by DockerCreateContainerCommand::Execute(), PodmanCreateContainerCommand::Execute(), DockerStartContainerCommand::Execute(), PodmanStartContainerCommand::Execute(), PodmanStopContainerCommand::Execute(), DockerStopContainerCommand::Execute(), PodmanRemoveContainerCommand::Execute(), DockerRemoveContainerCommand::Execute(), PodmanRestartContainerCommand::Execute(), and DockerRestartContainerCommand::Execute().
Variable Documentation
kContainerManagerLogName
const std::string kContainerManagerLogName = "cm_log"
Name used for container manager in google logging.
Definition at line 20 of file common.hpp.
Referenced by InitLogging().
kDockerApiBaseUrl
constexpr char kDockerApiBaseUrl[] = "http://localhost/v1.49/" inline constexpr
Definition at line 33 of file common.hpp.
Referenced by DockerApiRuntimeAvailableCommand::Execute(), DockerApiCreateContainerCommand::Execute(), DockerApiStartContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), DockerApiRestartContainerCommand::Execute(), and DockerApiRemoveContainerCommand::Execute().
kDockerUnixSocketPath
constexpr char kDockerUnixSocketPath[] = "/var/run/docker.sock" inline constexpr
Docker Unix socket path and API base URL for HTTP API communication.
Definition at line 32 of file common.hpp.
Referenced by DockerApiRuntimeAvailableCommand::Execute(), DockerApiCreateContainerCommand::Execute(), DockerApiStartContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), DockerApiRestartContainerCommand::Execute(), and DockerApiRemoveContainerCommand::Execute().
kEmptyString
const std::string kEmptyString = ""
Represents an empty string constant.
Definition at line 17 of file common.hpp.
Referenced by JsonRequestExecutorHandler::Execute(), and ProtoRequestExecutorHandler::Execute().
kMainShutdownPollMs
constexpr int kMainShutdownPollMs = 200 constexpr
Sleep interval (in milliseconds) for main thread shutdown polling.
Definition at line 23 of file common.hpp.
Referenced by main().
kMaxEntries
constexpr size_t kMaxEntries = 32 constexpr
Maximum number of entries for embedded database.
Definition at line 26 of file common.hpp.
kMaxKeyLen
constexpr size_t kMaxKeyLen = 32 constexpr
Maximum key length for embedded database entries.
Definition at line 29 of file common.hpp.
Referenced by EmbeddedDatabaseHandler::GetJson(), EmbeddedDatabaseHandler::RemoveKey(), EmbeddedDatabaseHandler::SaveJson(), and EmbeddedDatabaseHandler::UpdateField().
kPodmanApiBaseUrl
constexpr char kPodmanApiBaseUrl[] = "http://d/v3.0.0/" inline constexpr
Definition at line 37 of file common.hpp.
Referenced by PodmanApiRuntimeAvailableCommand::Execute(), PodmanApiCreateContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), and PodmanApiStopContainerCommand::Execute().
kPodmanUnixSocketPath
constexpr char kPodmanUnixSocketPath[] = "/run/user/1000/podman/podman.sock" inline constexpr
Podman Unix socket path and API base URL for HTTP API communication.
Definition at line 36 of file common.hpp.
Referenced by PodmanApiRuntimeAvailableCommand::Execute(), PodmanApiCreateContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), and PodmanApiStopContainerCommand::Execute().