Container Manager: unitTest/container_service_test.cpp File Reference
container_service_test.cpp File Reference
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include <memory>
#include <string>
#include <nlohmann/json.hpp>
#include "inc/command_factory.hpp"
#include "inc/container_service.hpp"
#include "inc/database_interface.hpp"
#include "inc/container_request.hpp"
#include "inc/common.hpp"
Classes
class MockDatabaseHandler
class ContainerServiceHandlerTest
Functions
TEST_F (ContainerServiceHandlerTest, HandleRequest_CreateContainer_Success)
TEST_F (ContainerServiceHandlerTest, HandleRequest_CreateContainer_Failure)
TEST_F (ContainerServiceHandlerTest, HandleRequest_StartContainer_Success)
TEST_F (ContainerServiceHandlerTest, HandleRequest_StartContainer_Failure)
TEST_F (ContainerServiceHandlerTest, HandleRequest_StopContainer_Success)
TEST_F (ContainerServiceHandlerTest, HandleRequest_StopContainer_Failure)
TEST_F (ContainerServiceHandlerTest, HandleRequest_RestartContainer_Success)
TEST_F (ContainerServiceHandlerTest, HandleRequest_RestartContainer_Failure)
TEST_F (ContainerServiceHandlerTest, HandleRequest_RemoveContainer_Success)
TEST_F (ContainerServiceHandlerTest, HandleRequest_RemoveContainer_Failure)
Function Documentation
TEST_F() [1/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_CreateContainer_Failure)
Definition at line 60 of file container_service_test.cpp.
{
     class FailingService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Error(StatusCode::NotFound, "fail"); }
     };
     ContainerRequest req;
     req.operation = CommandName::CreateContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("Error creating container")));
     FailingService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "error");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), CommandName::CreateContainer, Status::Error(), NotFound, and ContainerRequest::operation.
TEST_F() [2/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_CreateContainer_Success)
Definition at line 39 of file container_service_test.cpp.
{
     class TestService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Ok(); }
     };
     ContainerRequest req;
     req.operation = CommandName::CreateContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("created")));
     TestService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "success");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), CommandName::CreateContainer, Status::Ok(), and ContainerRequest::operation.
TEST_F() [3/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_RemoveContainer_Failure)
Definition at line 228 of file container_service_test.cpp.
{
     class FailingService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Error(StatusCode::PermissionDenied, "fail"); }
     };
     ContainerRequest req;
     req.operation = CommandName::RemoveContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("Error removing container")));
     FailingService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "error");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Error(), ContainerRequest::operation, PermissionDenied, and CommandName::RemoveContainer.
TEST_F() [4/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_RemoveContainer_Success)
Definition at line 207 of file container_service_test.cpp.
{
     class TestService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Ok(); }
     };
     ContainerRequest req;
     req.operation = CommandName::RemoveContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, RemoveKey(StrEq("test_container")));
     TestService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "success");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Ok(), ContainerRequest::operation, and CommandName::RemoveContainer.
TEST_F() [5/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_RestartContainer_Failure)
Definition at line 186 of file container_service_test.cpp.
{
     class FailingService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Error(StatusCode::Timeout, "fail"); }
     };
     ContainerRequest req;
     req.operation = CommandName::RestartContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("Error restarting container")));
     FailingService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "error");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Error(), ContainerRequest::operation, CommandName::RestartContainer, and Timeout.
TEST_F() [6/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_RestartContainer_Success)
Definition at line 165 of file container_service_test.cpp.
{
     class TestService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Ok(); }
     };
     ContainerRequest req;
     req.operation = CommandName::RestartContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("running")));
     TestService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "success");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Ok(), ContainerRequest::operation, and CommandName::RestartContainer.
TEST_F() [7/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_StartContainer_Failure)
Definition at line 102 of file container_service_test.cpp.
{
     class FailingService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Error(StatusCode::InvalidArgument, "fail"); }
     };
     ContainerRequest req;
     req.operation = CommandName::StartContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("Error running container")));
     FailingService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "error");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Error(), InvalidArgument, ContainerRequest::operation, and CommandName::StartContainer.
TEST_F() [8/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_StartContainer_Success)
Definition at line 81 of file container_service_test.cpp.
{
     class TestService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Ok(); }
     };
     ContainerRequest req;
     req.operation = CommandName::StartContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("running")));
     TestService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "success");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Ok(), ContainerRequest::operation, and CommandName::StartContainer.
TEST_F() [9/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_StopContainer_Failure)
Definition at line 144 of file container_service_test.cpp.
{
     class FailingService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Error(StatusCode::InternalError, "fail"); }
     };
     ContainerRequest req;
     req.operation = CommandName::StopContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("Error stopping container")));
     FailingService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "error");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Error(), InternalError, ContainerRequest::operation, and CommandName::StopContainer.
TEST_F() [10/10]
TEST_F (ContainerServiceHandlerTest , HandleRequest_StopContainer_Success)
Definition at line 123 of file container_service_test.cpp.
{
     class TestService : public ContainerServiceHandler {
     public:
         using ContainerServiceHandler::ContainerServiceHandler;
         Status ContainerOperations(const ContainerRequest&) override { return Status::Ok(); }
     };
     ContainerRequest req;
     req.operation = CommandName::StopContainer;
     req.container_name = "test_container";
     EXPECT_CALL(*db_handler, UpdateField(StrEq("test_container"), StrEq("status"), StrEq("stopped")));
     TestService test_service(*db_handler);
     auto result = test_service.HandleRequest(req);
     EXPECT_EQ(result["status"], "success");
     EXPECT_EQ(result["container"], "test_container");
 }
References ContainerRequest::container_name, ContainerServiceHandler::ContainerOperations(), ContainerServiceHandler::ContainerServiceHandler(), Status::Ok(), ContainerRequest::operation, and CommandName::StopContainer.