Container Manager: utils/inc/init_handler.hpp File Reference
init_handler.hpp File Reference
Declares project-wide initialization functions for the Container Manager application.
#include "inc/database_interface.hpp"
Functions
void InitLogging ()
Initializes logging.
void InitDatabase (IDatabaseHandler &db)
Initializes and clears the database.
void InitMessageQueue ()
Clears the POSIX message queue.
void InitMqttRetainedMessages ()
Clears retained MQTT messages.
void InitProject (IDatabaseHandler &db)
Initializes all enabled project subsystems.
Detailed Description
Declares project-wide initialization functions for the Container Manager application.
Provides initialization routines for logging, database, message queue, and MQTT subsystems. All functions are designed to be called at application startup to ensure a clean and ready state. The database initialization uses dependency injection for flexibility and testability.
Definition in file init_handler.hpp.
Function Documentation
InitDatabase()
void InitDatabase (IDatabaseHandler & db)
Initializes and clears the database.
Prepares the database for use and ensures it is in a clean state.
Parameters
db Reference to an IDatabaseHandler implementation.
db Reference to an IDatabaseHandler implementation.
Definition at line 33 of file init_handler.cpp.
{
     db.ClearDatabase();
 }
References IDatabaseHandler::ClearDatabase().
Referenced by InitProject().
InitLogging()
void InitLogging ()
Initializes logging.
Sets up the logging system (e.g., Google glog) for the application.
Initializes logging.
Definition at line 25 of file init_handler.cpp.
                    {
     google::InitGoogleLogging(kContainerManagerLogName.c_str());
 }
References kContainerManagerLogName.
Referenced by InitProject().
InitMessageQueue()
void InitMessageQueue ()
Clears the POSIX message queue.
Removes all messages from the POSIX message queue at startup.
Clears the POSIX message queue.
Unlinks the message queue to remove all pending messages.
Definition at line 41 of file init_handler.cpp.
{
     MessageQueueConfig mq_cfg;
     mq_unlink(mq_cfg.QueueName.c_str());
 }
References MessageQueueConfig::QueueName.
Referenced by InitProject().
InitMqttRetainedMessages()
void InitMqttRetainedMessages ()
Clears retained MQTT messages.
Removes all retained messages from the MQTT broker at startup.
Clears retained MQTT messages.
Definition at line 67 of file init_handler.cpp.
 {}
Referenced by InitProject().
InitProject()
void InitProject (IDatabaseHandler & db)
Initializes all enabled project subsystems.
Calls all necessary initialization routines for logging, database, message queue, and MQTT.
Parameters
db Reference to an IDatabaseHandler implementation.
Definition at line 75 of file init_handler.cpp.
{
     InitLogging();
     InitDatabase(db);
     InitMessageQueue();
     InitMqttRetainedMessages();
 }
References InitDatabase(), InitLogging(), InitMessageQueue(), and InitMqttRetainedMessages().
Referenced by main().