Container Manager: utils/src/init_handler.cpp File Reference
init_handler.cpp File Reference
Implements project-wide initialization functions.
#include "inc/init_handler.hpp"
#include <glog/logging.h>
#include <mqueue.h>
#include "inc/common.hpp"
#include "inc/redis_database.hpp"
Functions
void InitLogging ()
Initializes logging and clears the database before server startup.
void InitDatabase ()
Initializes and clears the database.
void InitMessageQueue ()
Clears the POSIX message queue.
void InitMqttRetainedMessages ()
Clears retained MQTT messages.
void InitProject ()
Initializes all enabled project subsystems.
Detailed Description
Implements project-wide initialization functions.
Definition in file init_handler.cpp.
Function Documentation
InitDatabase()
void InitDatabase ()
Initializes and clears the database.
Definition at line 21 of file init_handler.cpp.
                     {
     IDatabaseHandler& db = RedisDatabaseHandler::GetInstance();
     db.ClearDatabase();
 }
References IDatabaseHandler::ClearDatabase(), and RedisDatabaseHandler::GetInstance().
Referenced by InitProject().
InitLogging()
void InitLogging ()
Initializes logging and clears the database before server startup.
This function should be called at application startup to set up logging and ensure the database is in a clean state.
Initializes logging.
Definition at line 17 of file init_handler.cpp.
                    {
     google::InitGoogleLogging(kContainerManagerLogName.c_str());
 }
References kContainerManagerLogName.
Referenced by InitProject().
InitMessageQueue()
void InitMessageQueue ()
Clears the POSIX message queue.
Definition at line 26 of file init_handler.cpp.
{
     MessageQueueConfig mq_cfg;
     mq_unlink(mq_cfg.QueueName.c_str());
 }
References MessageQueueConfig::QueueName.
Referenced by InitProject().
InitMqttRetainedMessages()
void InitMqttRetainedMessages ()
Clears retained MQTT messages.
Definition at line 45 of file init_handler.cpp.
 {}
Referenced by InitProject().
InitProject()
void InitProject ()
Initializes all enabled project subsystems.
Definition at line 48 of file init_handler.cpp.
                    {
     InitLogging();
     InitDatabase();
     InitMessageQueue();
     InitMqttRetainedMessages();
 }
References InitDatabase(), InitLogging(), InitMessageQueue(), and InitMqttRetainedMessages().
Referenced by main().