Container Manager: main.cpp File Reference
main.cpp File Reference
Entry point for the Container Manager service.
#include <memory>
#include <thread>
#include <vector>
#include <atomic>
#include <csignal>
#include <iostream>
#include <glog/logging.h>
#include "inc/common.hpp"
#include "inc/init_handler.hpp"
#include "inc/container_service.hpp"
#include "inc/json_request_executor.hpp"
#include "inc/null_security_provider.hpp"
#include "inc/embedded_database.hpp"
Functions
void SignalHandler (int signum)
Signal handler for graceful shutdown (SIGINT/SIGTERM).
int main ()
Main entry point for the Container Manager service.
Variables
std::atomic< bool > shutdown_requested {false}
Atomic flag to signal shutdown to all protocol consumers.
Detailed Description
Entry point for the Container Manager service.
This file contains the main function for the Container Manager project. It initializes the selected database backend, sets up the service and protocol handlers, and starts protocol consumers (REST, MQTT, Message Queue, D-Bus) in separate threads. The application supports modular protocol and data format selection, pluggable database backends, and optional encryption (AES-GCM or ChaCha20). Graceful shutdown is handled via signal handlers.
Definition in file main.cpp.
Function Documentation
main()
int main ()
Main entry point for the Container Manager service.
Initializes logging, selects the database backend (Redis or Embedded), sets up the service handler, and starts protocol consumers for REST, MQTT, POSIX Message Queue, and D-Bus (if enabled). Handles graceful shutdown and joins all protocol threads before exiting.
Returns
int Exit code.
Definition at line 89 of file main.cpp.
            {
     // Print enabled features at startup
     std::cout << "==== Container Manager v0.7.0 ====" << std::endl;
     std::cout << "Features enabled:" << std::endl;
 #if ENABLE_REST
     std::cout << "  ✓ REST/HTTP Server" << std::endl;
 #endif
 #if ENABLE_MQTT
     std::cout << "  ✓ MQTT Subscriber" << std::endl;
 #endif
 #if ENABLE_MSGQUEUE
     std::cout << "  ✓ POSIX Message Queue" << std::endl;
 #endif
 #if ENABLE_DBUS
     std::cout << "  ✓ D-Bus Consumer" << std::endl;
 #endif
 #if ENABLE_PROTOBUF
     std::cout << "  ✓ Protobuf Support" << std::endl;
 #else
     std::cout << "  ✓ JSON Support" << std::endl;
 #endif
 #if ENABLE_REDIS
     std::cout << "  ✓ Redis Database" << std::endl;
 #else
     std::cout << "  ✓ Embedded Database" << std::endl;
 #endif
 #if ENABLE_ENCRYPTION
     #if defined(SECURITY_ALGORITHM_AES_GCM)
         std::cout << "  🔒 Security: AES-256-GCM" << std::endl;
     #elif defined(SECURITY_ALGORITHM_CHACHA20)
         std::cout << "  🔒 Security: ChaCha20-Poly1305 (Automotive)" << std::endl;
     #endif
 #else
     std::cout << "  🔓 Security: DISABLED" << std::endl;
 #endif
     std::cout << "===================================" << std::endl;
     // Select database backend (Redis or Embedded)
 #if ENABLE_REDIS
     auto db = std::make_unique<RedisDatabaseHandler>();
 #else
     auto db = std::make_unique<EmbeddedDatabaseHandler>();
 #endif
     // Create the service handler for container operations
     auto service = std::make_unique<ContainerServiceHandler>(*db);
     // Initialize project (logging, DB, etc.)
     InitProject(*db);
     // Create security provider based on CMake configuration
     std::unique_ptr<ISecurityProvider> security_provider;
 #if defined(SECURITY_ALGORITHM_AES_GCM)
     security_provider = std::make_unique<AesGcmSecurityProvider>();
     std::cout << "🔑 AES-256-GCM Security Provider initialized" << std::endl;
 #elif defined(SECURITY_ALGORITHM_CHACHA20)
     security_provider = std::make_unique<ChaCha20SecurityProvider>();
     std::cout << "🔑 ChaCha20-Poly1305 Security Provider initialized (Automotive OTA)" << std::endl;
 #else
     security_provider = std::make_unique<NullSecurityProvider>();
     std::cout << "🔓 Null Security Provider initialized (encryption disabled)" << std::endl;
 #endif
     // Create request executor with security provider reference
 #if ENABLE_PROTOBUF
     auto executor = std::make_shared<ProtoRequestExecutorHandler>(*db, *service, *security_provider);
 #else
     auto executor = std::make_shared<JsonRequestExecutorHandler>(*db, *service, *security_provider);
 #endif
     // Register signal handlers for graceful shutdown
     std::signal(SIGINT, SignalHandler);
     std::signal(SIGTERM, SignalHandler);
     // Vector to hold protocol consumer threads
     std::vector<std::thread> protocol_threads;
     // Start REST/HTTP server in a separate thread if enabled
 #if ENABLE_REST
     ServerConfig server_cfg;
     auto server = std::make_shared<HttpServerHandler>(server_cfg.ThreadPoolSize, executor);
     // Exact host and port values for lambda function capture
     std::string host = server_cfg.Host;
     int port = server_cfg.Port;
     protocol_threads.emplace_back([server, host, port]() {
         server->Start(host, port);
     });
 #endif
     // Start MQTT subscriber in a separate thread if enabled
 #if ENABLE_MQTT
     MqttConfig mqtt_cfg;
     auto mqtt_consumer = std::make_shared<MosquittoMqttSubscriber>(
         mqtt_cfg.BrokerAddress, mqtt_cfg.BrokerPort, mqtt_cfg.Topic, executor);
     protocol_threads.emplace_back([mqtt_consumer]() {
         mqtt_consumer->Start();
     });
 #endif
     // Start POSIX Message Queue consumer in a separate thread if enabled
 #if ENABLE_MSGQUEUE
     MessageQueueConfig mq_cfg;
     auto mq_consumer = std::make_shared<MessageQueueConsumer>(mq_cfg, executor);
     protocol_threads.emplace_back([mq_consumer]() {
         mq_consumer->Start();
     });
 #endif
     // Start D-Bus consumer in a separate thread if enabled
 #if ENABLE_DBUS
     DbusConfig dbus_cfg;
     auto dbus_consumer = std::make_shared<DBusConsumer>(dbus_cfg, executor);
     protocol_threads.emplace_back([dbus_consumer]() {
         dbus_consumer->Start();
     });
 #endif
     // Main loop: wait for shutdown signal
     while (!shutdown_requested) {
         std::this_thread::sleep_for(std::chrono::milliseconds(kMainShutdownPollMs));
     }
     // Stop all protocol consumers gracefully
 #if ENABLE_REST
     server->Stop();
 #endif
 #if ENABLE_MQTT
     mqtt_consumer->Stop();
 #endif
 #if ENABLE_MSGQUEUE
     mq_consumer->Stop();
 #endif
 #if ENABLE_DBUS
     dbus_consumer->Stop();
 #endif
     // Join all protocol threads to ensure clean shutdown
     for (auto& t : protocol_threads) {
         if (t.joinable()) {
             t.join();
         }
     }
     // Shutdown logging and exit
     google::ShutdownGoogleLogging();
     return 0;
 }
References MqttConfig::BrokerAddress, MqttConfig::BrokerPort, ServerConfig::Host, InitProject(), kMainShutdownPollMs, ServerConfig::Port, shutdown_requested, SignalHandler(), ServerConfig::ThreadPoolSize, and MqttConfig::Topic.
SignalHandler()
void SignalHandler (int signum)
Signal handler for graceful shutdown (SIGINT/SIGTERM).
Parameters
signum Signal number.
Definition at line 75 of file main.cpp.
{
     shutdown_requested = true;
     std::cout << "Shutdown signal received. Stopping protocol consumers..." << std::endl;
 }
References shutdown_requested.
Referenced by main().
Variable Documentation
shutdown_requested
shutdown_requested {false}
Atomic flag to signal shutdown to all protocol consumers.
Definition at line 69 of file main.cpp.
Referenced by main(), and SignalHandler().