Container Manager: protobuf_container_5fmanager_2eproto Namespace Reference
protobuf_container_5fmanager_2eproto Namespace Reference
Classes
struct StaticDescriptorInitializer
struct TableStruct
Functions
void InitDefaults ()
const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE (protodesc_cold)
void protobuf_AssignDescriptors ()
void protobuf_AssignDescriptorsOnce ()
void protobuf_RegisterTypes (const ::std::string &) GOOGLE_PROTOBUF_ATTRIBUTE_COLD
void AddDescriptorsImpl ()
void AddDescriptors ()
Variables
extern ::google::protobuf::internal::SCCInfo< 0 > scc_info_ContainerParameters
::google::protobuf::internal::SCCInfo< 1 > scc_info_ContainerRequest
::google::protobuf::Metadata file_level_metadata [2]
struct protobuf_container_5fmanager_2eproto::StaticDescriptorInitializer static_descriptor_initializer
Function Documentation
AddDescriptors()
void protobuf_container_5fmanager_2eproto::AddDescriptors ()
Definition at line 141 of file container_manager.pb.cc.
                       {
   static ::google::protobuf::internal::once_flag once;
   ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
 }
References AddDescriptorsImpl().
Referenced by protobuf_AssignDescriptors(), and protobuf_container_5fmanager_2eproto::StaticDescriptorInitializer::StaticDescriptorInitializer().
AddDescriptorsImpl()
void protobuf_container_5fmanager_2eproto::AddDescriptorsImpl ()
Definition at line 123 of file container_manager.pb.cc.
{
   InitDefaults();
   static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
       "\n\027container_manager.proto\022\020containermana"
       "ger\"\205\001\n\023ContainerParameters\022\026\n\016container"
       "_name\030\001 \001(\t\022\014\n\004cpus\030\002 \001(\t\022\016\n\006memory\030\003 \001("
       "\t\022\014\n\004pids\030\004 \001(\t\022\026\n\016restart_policy\030\005 \001(\t\022"
       "\022\n\nimage_name\030\006 \001(\t\"q\n\020ContainerRequest\022"
       "\017\n\007runtime\030\001 \001(\t\022\021\n\toperation\030\002 \001(\t\0229\n\np"
       "arameters\030\003 \003(\0132%.containermanager.Conta"
       "inerParametersb\006proto3"
   };
   ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
       descriptor, 302);
   ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
     "container_manager.proto", &protobuf_RegisterTypes);
 }
References GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(), InitDefaults(), and protobuf_RegisterTypes().
Referenced by AddDescriptors().
GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE()
const ::google::protobuf::uint32 TableStruct::offsets [] protobuf_container_5fmanager_2eproto::GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE (protodesc_cold)
Referenced by AddDescriptorsImpl().
InitDefaults()
void protobuf_container_5fmanager_2eproto::InitDefaults ()
Definition at line 67 of file container_manager.pb.cc.
                     {
   ::google::protobuf::internal::InitSCC(&scc_info_ContainerParameters.base);
   ::google::protobuf::internal::InitSCC(&scc_info_ContainerRequest.base);
 }
References scc_info_ContainerParameters, and scc_info_ContainerRequest.
Referenced by AddDescriptorsImpl().
protobuf_AssignDescriptors()
void protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptors ()
Definition at line 105 of file container_manager.pb.cc.
{
   AddDescriptors();
   AssignDescriptors(
       "container_manager.proto", schemas, file_default_instances, TableStruct::offsets,
       file_level_metadata, NULL, NULL);
 }
References AddDescriptors(), file_level_metadata, and protobuf_container_5fmanager_2eproto::TableStruct::offsets.
Referenced by protobuf_AssignDescriptorsOnce().
protobuf_AssignDescriptorsOnce()
void protobuf_container_5fmanager_2eproto::protobuf_AssignDescriptorsOnce ()
Definition at line 112 of file container_manager.pb.cc.
{
   static ::google::protobuf::internal::once_flag once;
   ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
 }
References protobuf_AssignDescriptors().
Referenced by containermanager::ContainerParameters::descriptor(), containermanager::ContainerRequest::descriptor(), containermanager::ContainerParameters::GetMetadata(), containermanager::ContainerRequest::GetMetadata(), and protobuf_RegisterTypes().
protobuf_RegisterTypes()
void protobuf_container_5fmanager_2eproto::protobuf_RegisterTypes (const ::std::string &)
Definition at line 118 of file container_manager.pb.cc.
{
   protobuf_AssignDescriptorsOnce();
   ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
 }
References file_level_metadata, and protobuf_AssignDescriptorsOnce().
Referenced by AddDescriptorsImpl().
Variable Documentation
file_level_metadata
::google::protobuf::Metadata protobuf_container_5fmanager_2eproto::file_level_metadata[2]
Definition at line 72 of file container_manager.pb.cc.
Referenced by containermanager::ContainerParameters::descriptor(), containermanager::ContainerRequest::descriptor(), containermanager::ContainerParameters::GetMetadata(), containermanager::ContainerRequest::GetMetadata(), protobuf_AssignDescriptors(), and protobuf_RegisterTypes().
scc_info_ContainerParameters
google::protobuf::internal::SCCInfo< 0 > protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters
Initial value:
=
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsContainerParameters}, {}}
Definition at line 23 of file container_manager.pb.cc.
Referenced by containermanager::ContainerParameters::ContainerParameters(), containermanager::ContainerParameters::default_instance(), and InitDefaults().
scc_info_ContainerRequest
::google::protobuf::internal::SCCInfo<1> protobuf_container_5fmanager_2eproto::scc_info_ContainerRequest
Initial value:
=
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsContainerRequest}, {
      &protobuf_container_5fmanager_2eproto::scc_info_ContainerParameters.base,}}
Definition at line 63 of file container_manager.pb.cc.
Referenced by containermanager::ContainerRequest::ContainerRequest(), containermanager::ContainerRequest::default_instance(), and InitDefaults().
static_descriptor_initializer
struct protobuf_container_5fmanager_2eproto::StaticDescriptorInitializer protobuf_container_5fmanager_2eproto::static_descriptor_initializer