Container Manager: Status Struct Reference
Status Struct Reference
Represents the result of an operation, including a code and message.
#include <status.hpp>
Public Member Functions
Status (StatusCode c=StatusCode::Success, std::string msg="OK")
Constructs a Status with the given code and message.
bool ok () const
Checks if the status represents success.
Static Public Member Functions
static Status Ok ()
Returns a success Status.
static Status Error (StatusCode code, const std::string &msg)
Returns an error Status with the given code and message.
Public Attributes
StatusCode code
The status code.
std::string message
A human-readable message describing the status.
Detailed Description
Represents the result of an operation, including a code and message.
Definition at line 32 of file status.hpp.
Constructor & Destructor Documentation
Status()
Status::Status (StatusCode c = StatusCode::Success, std::string msg = "OK") inline
Constructs a Status with the given code and message.
Parameters
c The status code.
msg The status message (default: "OK").
Definition at line 41 of file status.hpp.
         : code(c), message(std::move(msg)) {}
Member Function Documentation
Error()
static Status Status::Error (StatusCode code, const std::string & msg) inline static
Returns an error Status with the given code and message.
Parameters
code The error status code.
msg The error message.
Returns
Status with the specified code and message.
Definition at line 56 of file status.hpp.
 { return {code, msg}; }
References code.
Referenced by DockerRuntimeAvailableCommand::Execute(), DockerApiRuntimeAvailableCommand::Execute(), PodmanRuntimeAvailableCommand::Execute(), PodmanApiRuntimeAvailableCommand::Execute(), ProtoRequestExecutorHandler::Execute(), JsonRequestExecutorHandler::Execute(), DockerCreateContainerCommand::Execute(), PodmanApiCreateContainerCommand::Execute(), DockerApiCreateContainerCommand::Execute(), PodmanCreateContainerCommand::Execute(), DockerStartContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), DockerApiStartContainerCommand::Execute(), PodmanStartContainerCommand::Execute(), DockerStopContainerCommand::Execute(), PodmanStopContainerCommand::Execute(), PodmanApiStopContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), DockerRemoveContainerCommand::Execute(), DockerApiRestartContainerCommand::Execute(), PodmanRemoveContainerCommand::Execute(), DockerRestartContainerCommand::Execute(), DockerApiRemoveContainerCommand::Execute(), PodmanRestartContainerCommand::Execute(), and TEST_F().
Ok()
static Status Status::Ok () inline static
Returns a success Status.
Returns
Status with code Success and message "OK".
Definition at line 48 of file status.hpp.
 { return {StatusCode::Success, "OK"}; }
References Success.
Referenced by DockerRuntimeAvailableCommand::Execute(), PodmanRuntimeAvailableCommand::Execute(), DockerApiRuntimeAvailableCommand::Execute(), PodmanApiRuntimeAvailableCommand::Execute(), DockerCreateContainerCommand::Execute(), DockerApiCreateContainerCommand::Execute(), PodmanCreateContainerCommand::Execute(), PodmanApiCreateContainerCommand::Execute(), DockerStartContainerCommand::Execute(), PodmanStartContainerCommand::Execute(), DockerApiStartContainerCommand::Execute(), PodmanApiStartContainerCommand::Execute(), DockerStopContainerCommand::Execute(), PodmanApiStopContainerCommand::Execute(), DockerApiStopContainerCommand::Execute(), PodmanStopContainerCommand::Execute(), DockerRemoveContainerCommand::Execute(), DockerApiRestartContainerCommand::Execute(), PodmanRemoveContainerCommand::Execute(), DockerRestartContainerCommand::Execute(), PodmanRestartContainerCommand::Execute(), DockerApiRemoveContainerCommand::Execute(), and TEST_F().
ok()
bool Status::ok () const inline
Checks if the status represents success.
Returns
true if status code is Success, false otherwise.
Definition at line 62 of file status.hpp.
 { return code == StatusCode::Success; }
References code, and Success.
Referenced by ContainerServiceHandler::HandleRequest().
Member Data Documentation
code
StatusCode Status::code
The status code.
Definition at line 33 of file status.hpp.
Referenced by Error(), ProtoRequestExecutorHandler::Execute(), JsonRequestExecutorHandler::Execute(), and ok().
message
std::string Status::message
A human-readable message describing the status.
Definition at line 34 of file status.hpp.
Referenced by JsonRequestExecutorHandler::Execute(), and ProtoRequestExecutorHandler::Execute().
The documentation for this struct was generated from the following file:
utils/inc/status.hpp