apiVersion: v1
kind: Pod
metadata:
  name: { { POD_NAME } }
  labels:
    app: { { CONTAINER_NAME } }
spec:
  containers:
    - name: { { CONTAINER_NAME } }
      image: { { IMAGE_NAME } }
      resources:
        limits:
          cpu: "{{CPU_LIMIT}}"
          memory: "{{MEMORY_LIMIT}}Mi"
      ports:
        - containerPort: 80
  restartPolicy: Always
