# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container_manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='container_manager.proto',
  package='containermanager',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17\x63ontainer_manager.proto\x12\x10\x63ontainermanager\"\x85\x01\n\x13\x43ontainerParameters\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63pus\x18\x02 \x01(\t\x12\x0e\n\x06memory\x18\x03 \x01(\t\x12\x0c\n\x04pids\x18\x04 \x01(\t\x12\x16\n\x0erestart_policy\x18\x05 \x01(\t\x12\x12\n\nimage_name\x18\x06 \x01(\t\"q\n\x10\x43ontainerRequest\x12\x0f\n\x07runtime\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x39\n\nparameters\x18\x03 \x03(\x0b\x32%.containermanager.ContainerParametersb\x06proto3')
)




_CONTAINERPARAMETERS = _descriptor.Descriptor(
  name='ContainerParameters',
  full_name='containermanager.ContainerParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='container_name', full_name='containermanager.ContainerParameters.container_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpus', full_name='containermanager.ContainerParameters.cpus', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory', full_name='containermanager.ContainerParameters.memory', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pids', full_name='containermanager.ContainerParameters.pids', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='restart_policy', full_name='containermanager.ContainerParameters.restart_policy', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='containermanager.ContainerParameters.image_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=179,
)


_CONTAINERREQUEST = _descriptor.Descriptor(
  name='ContainerRequest',
  full_name='containermanager.ContainerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime', full_name='containermanager.ContainerRequest.runtime', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='operation', full_name='containermanager.ContainerRequest.operation', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parameters', full_name='containermanager.ContainerRequest.parameters', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=294,
)

_CONTAINERREQUEST.fields_by_name['parameters'].message_type = _CONTAINERPARAMETERS
DESCRIPTOR.message_types_by_name['ContainerParameters'] = _CONTAINERPARAMETERS
DESCRIPTOR.message_types_by_name['ContainerRequest'] = _CONTAINERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContainerParameters = _reflection.GeneratedProtocolMessageType('ContainerParameters', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERPARAMETERS,
  __module__ = 'container_manager_pb2'
  # @@protoc_insertion_point(class_scope:containermanager.ContainerParameters)
  ))
_sym_db.RegisterMessage(ContainerParameters)

ContainerRequest = _reflection.GeneratedProtocolMessageType('ContainerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINERREQUEST,
  __module__ = 'container_manager_pb2'
  # @@protoc_insertion_point(class_scope:containermanager.ContainerRequest)
  ))
_sym_db.RegisterMessage(ContainerRequest)


# @@protoc_insertion_point(module_scope)
