# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: container_manager.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ontainer_manager.proto\x12\x10\x63ontainermanager\"\x85\x01\n\x13\x43ontainerParameters\x12\x16\n\x0e\x63ontainer_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63pus\x18\x02 \x01(\t\x12\x0e\n\x06memory\x18\x03 \x01(\t\x12\x0c\n\x04pids\x18\x04 \x01(\t\x12\x16\n\x0erestart_policy\x18\x05 \x01(\t\x12\x12\n\nimage_name\x18\x06 \x01(\t\"q\n\x10\x43ontainerRequest\x12\x0f\n\x07runtime\x18\x01 \x01(\t\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x39\n\nparameters\x18\x03 \x03(\x0b\x32%.containermanager.ContainerParametersb\x06proto3')



_CONTAINERPARAMETERS = DESCRIPTOR.message_types_by_name['ContainerParameters']
_CONTAINERREQUEST = DESCRIPTOR.message_types_by_name['ContainerRequest']
ContainerParameters = _reflection.GeneratedProtocolMessageType('ContainerParameters', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERPARAMETERS,
  '__module__' : 'container_manager_pb2'
  # @@protoc_insertion_point(class_scope:containermanager.ContainerParameters)
  })
_sym_db.RegisterMessage(ContainerParameters)

ContainerRequest = _reflection.GeneratedProtocolMessageType('ContainerRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONTAINERREQUEST,
  '__module__' : 'container_manager_pb2'
  # @@protoc_insertion_point(class_scope:containermanager.ContainerRequest)
  })
_sym_db.RegisterMessage(ContainerRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTAINERPARAMETERS._serialized_start=46
  _CONTAINERPARAMETERS._serialized_end=179
  _CONTAINERREQUEST._serialized_start=181
  _CONTAINERREQUEST._serialized_end=294
# @@protoc_insertion_point(module_scope)